# -*- coding: utf-8 -*-
"""Partea 5 - Sec. XI - XV d.Hr. (Regatul Ungariei, formarea statelor românești)"""
EVENTS = [
 dict(
  titlu="Campania lui Ștefan I împotriva voievodatului lui Gyula",
  tip="Campanie / cucerire",
  data_start="1003", data_end="1003", an_start=1003, an_end=1003,
  secol="sec. XI d.Hr.", secol_n=11,
  locatie="Alba Iulia (Transilvania)",
  zona_aprox=0, judet="Alba", regiune="Transilvania",
  lat=46.07, lng=23.57,
  participanti="Regatul Ungariei (Ștefan I) vs. voievodatul lui Gyula (Iuliu cel Tânăr)",
  descriere="Regele Ștefan I al Ungariei atacă voievodatul condus de Gyula, cu centrul la Alba Iulia, pentru a-și extinde autoritatea la est de Tisa. Gyula este luat prizonier, iar teritoriul său este anexat, consolidând stăpânirea maghiară în Transilvania.",
  rezultat="Anexarea voievodatului lui Gyula la Regatul Ungariei",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XI d.Hr., pct. 1"),
 dict(
  titlu="Războiul împotriva lui Ahtum (Banat)",
  tip="Război / cucerire",
  data_start="c. 1003", data_end="c. 1008", an_start=1003, an_end=1008,
  secol="sec. XI d.Hr.", secol_n=11,
  locatie="Banat: reședința Morisena (Cenad, jud. Timiș)",
  zona_aprox=0, judet="Timiș", regiune="Banat",
  lat=46.13, lng=20.58,
  participanti="Regatul Ungariei (Ștefan I, generalul Csanád) vs. voievodatul lui Ahtum",
  descriere="Regele Ștefan I trimite o armată condusă de generalul Csanád împotriva voievodatului lui Ahtum din Banat. Ahtum este ucis în luptă, iar reședința sa de la Morisena este cucerită; Banatul intră sub stăpânire ungară (datarea între c. 1003 și 1008 este discutată).",
  rezultat="Cucerirea Banatului; uciderea lui Ahtum",
  teritoriu="da",
  observatii="Datarea exactă este disputată (1003–1028 în sursă; majoritatea istoricilor: c. 1008).",
  sursa="batalii.csv — sec. XI d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Chiraleș (pecenegi și uzi)",
  tip="Bătălie",
  data_start="1068", data_end="1068", an_start=1068, an_end=1068,
  secol="sec. XI d.Hr.", secol_n=11,
  locatie="Chiraleș (județul Bistrița-Năsăud), Transilvania de nord",
  zona_aprox=0, judet="Bistrița-Năsăud", regiune="Transilvania",
  lat=47.06, lng=24.32,
  participanti="Regatul Ungariei (Solomon, Géza, Ladislau) vs. pecenegi și uzi",
  descriere="Una dintre cele mai răsunătoare ciocniri militare din Transilvania medievală timpurie: o armată mare de pecenegi și uzi pătrunde în Transilvania și Bihor pentru jaf. La întoarcere, migratorii sunt prinși și zdrobiți complet în apropierea localității Chiraleș de trupele regelui Solomon și ale prinților Géza și Ladislau.",
  rezultat="Zdrobrea completă a invadatorilor",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XI d.Hr., pct. 2"),
 dict(
  titlu="Marea invazie a pecenegilor (1048)",
  tip="Invazie / conflict",
  data_start="1048", data_end="1048", an_start=1048, an_end=1048,
  secol="sec. XI d.Hr.", secol_n=11,
  locatie="Dunărea de Jos, Dobrogea (tema bizantină Paristrion)",
  zona_aprox=1, judet="Constanța / Tulcea", regiune="Dobrogea",
  lat=44.3, lng=27.8,
  participanti="Pecenegi (hanul Tyrah, peste 80.000) vs. Imperiul Bizantin și pecenegul rival Kegen",
  descriere="Peste 80.000 de pecenegi conduși de hanul Tyrah trec Dunărea înghețată, declanșând un conflict devastator cu garnizoanele bizantine și cu facțiunea rivală a pecenegului Kegen. Bizanțul este obligat să le permită așezarea în zonă, schimbând echilibrul etnic al Dobrogei.",
  rezultat="Așezarea pecenegilor în Imperiu (ca foederati)",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XI d.Hr., pct. 3"),
 dict(
  titlu="Revolta conducătorilor locali din Dobrogea (Tatos, Sestlav, Saca)",
  tip="Revoltă / răscoală",
  data_start="c. 1070", data_end="c. 1090", an_start=1070, an_end=1090,
  secol="sec. XI d.Hr.", secol_n=11,
  locatie="Dobrogea: Silistra (Tatos), Vicina (Sestlav), fortărețe dunărene",
  zona_aprox=1, judet="Constanța / Tulcea", regiune="Dobrogea",
  lat=44.5, lng=28.3,
  participanti="Conducători locali (Tatos la Silistra, Sestlav la Vicina, Saca) vs. Imperiul Bizantin",
  descriere="Populația din Dobrogea (români, pecenegi asimilați, bulgari) se răscoală împotriva abuzurilor fiscale ale Constantinopolului. Trei conducători locali preiau controlul unor fortărețe dunărene și duc lupte cu bizantinii, iar confruntările se încheie spre sfârșitul secolului, când împăratul Alexie I Comnen restaurează autoritatea imperială.",
  rezultat="Restaurarea autorității bizantine după decenii de revoltă",
  teritoriu="da",
  observatii="Locațiile exacte (Vicina) sunt disputate.",
  sursa="batalii.csv — sec. XI d.Hr., pct. 3"),
 dict(
  titlu="Cucerirea și consolidarea stăpânirii maghiare în Transilvania",
  tip="Cucerire / conflicte de rezistență",
  data_start="c. 1100", data_end="c. 1199", an_start=1100, an_end=1199,
  secol="sec. XII d.Hr.", secol_n=12,
  locatie="Transilvania (estul și sudul arcului carpatic)",
  zona_aprox=1, judet="—", regiune="Transilvania",
  lat=46.0, lng=24.5,
  participanti="Regatul Ungariei vs. formațiuni politice locale (bannate, cnezate, voievodate românești, enclave pecenego-cumane)",
  descriere="Regatul Ungariei își extinde treptat controlul militar spre estul și sudul Transilvaniei. Pentru a-și securiza noile frontiere în fața nomazilor, regii folosesc fortificații de pământ și lemn și încep colonizarea secuilor și sașilor; procesul întâmpină rezistență din partea formațiunilor locale, cu prezență militară maghiară constantă.",
  rezultat="Consolidarea stăpânirii maghiare; integrarea treptată a Transilvaniei",
  teritoriu="da",
  observatii="Proces pe un secol; nu este un singur conflict.",
  sursa="batalii.csv — sec. XII d.Hr., pct. 1"),
 dict(
  titlu="Invaziile cumanilor și pecenegilor peste trecătorii Carpaților",
  tip="Raiduri / hărțuieli de frontieră",
  data_start="c. 1100", data_end="c. 1199", an_start=1100, an_end=1199,
  secol="sec. XII d.Hr.", secol_n=12,
  locatie="Trecătoriile Carpaților și zonele montane (estul Transilvaniei)",
  zona_aprox=1, judet="—", regiune="Transilvania / Moldova",
  lat=45.9, lng=25.8,
  participanti="Cumani și pecenegi vs. garnizoane maghiare și secuiești",
  descriere="Cumanii, așezați în zonele de câmpie de la sud și est de Carpați, lansează atacuri repetate peste munți în Transilvania și peste Dunăre în Imperiul Bizantin. Zonele montane și trecătorile devin teatrul unor hărțuieli constante între garnizoanele maghiare/secuiești și călăreții nomazi.",
  rezultat="Raiduri repetate; consolidarea granițelor maghiare cu secui și sași",
  teritoriu="da",
  observatii="Eveniment tip.",
  sursa="batalii.csv — sec. XII d.Hr., pct. 2"),
 dict(
  titlu="Războiul bizantino-maghiar (1127–1129)",
  tip="Război",
  data_start="1127", data_end="1129", an_start=1127, an_end=1129,
  secol="sec. XII d.Hr.", secol_n=12,
  locatie="Dunărea de Jos, Banat, Belgrad și Branișevo",
  zona_aprox=1, judet="—", regiune="Banat / Dunărea de Jos",
  lat=44.8, lng=21.5,
  participanti="Regatul Ungariei (Ștefan al II-lea) vs. Imperiul Bizantin",
  descriere="Regele Ștefan al II-lea al Ungariei atacă Imperiul Bizantin, distrugând Belgradul și Branișevo. Bizantinii răspund printr-o contraofensivă puternică, controlând militar pentru scurt timp zone de la Dunărea de Jos și din Banat.",
  rezultat="Contraofensivă bizantină; control temporar asupra Dunării de Jos",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XII d.Hr., pct. 3"),
 dict(
  titlu="Campaniile lui Manuel I Comnen la Dunăre",
  tip="Campanii / expediții",
  data_start="1151", data_end="1156", an_start=1151, an_end=1156,
  secol="sec. XII d.Hr.", secol_n=12,
  locatie="Dunărea de Mijloc și de Jos, inclusiv părți din Banat și Dobrogea",
  zona_aprox=1, judet="—", regiune="Banat / Dobrogea",
  lat=44.6, lng=27.0,
  participanti="Imperiul Bizantin (Manuel I Comnen) vs. Regatul Ungariei",
  descriere="Împăratul bizantin conduce expediții militare în regiunea Dunării de Mijloc și de Jos pentru a pedepsi incursiunile maghiare și a-și securiza granița nordică, transformând regiunile de frontieră (inclusiv părți din Banat și Dobrogea) în zone de război active.",
  rezultat="Securizarea temporară a graniței bizantine; tensiuni persistente",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XII d.Hr., pct. 3"),
 dict(
  titlu="Răscoala Asăneștilor și sprijinul militar de la nord de Dunăre",
  tip="Răscoală / campanie",
  data_start="1185", data_end="c. 1190", an_start=1185, an_end=1190,
  secol="sec. XII d.Hr.", secol_n=12,
  locatie="Baza de la nord de Dunăre (Muntenia) și sudul Dunării",
  zona_aprox=1, judet="—", regiune="Muntenia / Dobrogea",
  lat=44.4, lng=26.3,
  participanti="Frații Petru și Asan (vlahi) și cumani vs. Imperiul Bizantin",
  descriere="În timpul revoltei fraților Petru și Asan împotriva Bizanțului (care duce la crearea Imperiului Vlaho-Bulgar), teritoriul de la nord de Dunăre (Muntenia de azi) servește ca loc de refugiu și bază de recrutare pentru armatele de vlahi și cumani, care trec fluviul pentru a ataca garnizoanele bizantine.",
  rezultat="Înființarea Imperiului Vlaho-Bulgar (1185–1186)",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XII d.Hr., pct. 4"),
 dict(
  titlu="Marea invazie mongolă (tătară) din 1241–1242",
  tip="Invazie / devastare",
  data_start="1241", data_end="1242", an_start=1241, an_end=1242,
  secol="sec. XIII d.Hr.", secol_n=13,
  locatie="Moldova, Muntenia și Transilvania (Rodna, Bistrița, Sibiu, Alba Iulia)",
  zona_aprox=1, judet="—", regiune="Moldova / Muntenia / Transilvania",
  lat=46.5, lng=25.0,
  participanti="Imperiul Mongol (Batu Han, Subutai) vs. cumani, vlahi și Regatul Ungariei",
  descriere="Cel mai distructiv conflict militar al secolului: armatele mongole atacă pe mai multe coloane. În Moldova și Muntenia zdrobesc rezistența locală (inclusiv a cumanilor și vlahilor); în Transilvania pătrund prin pasurile Rodna, Bârgău și Oituz. Orașe înfloritoare precum Rodna, Bistrița, Sibiu și Alba Iulia sunt asediate, cucerite și complet distruse.",
  rezultat="Decimarea populației; distrugerea orașelor; vid de putere ulterior",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XIII d.Hr., pct. 1"),
 dict(
  titlu="Revolta cneazului Litovoi",
  tip="Revoltă / bătălie",
  data_start="1277", data_end="1279", an_start=1277, an_end=1279,
  secol="sec. XIII d.Hr.", secol_n=13,
  locatie="Oltenia și probabil sudul Transilvaniei",
  zona_aprox=1, judet="—", regiune="Oltenia / Transilvania",
  lat=44.9, lng=23.5,
  participanti="Voievodul român Litovoi vs. Regatul Ungariei (Ladislau al IV-lea)",
  descriere="Voievodul român Litovoi, stăpân pe un teritoriu în Oltenia și probabil în sudul Transilvaniei, refuză să mai plătească tribut regelui maghiar Ladislau al IV-lea și ocupă pământuri ale coroanei. În bătălia care urmează, Litovoi moare pe câmpul de luptă, iar fratele său, Bărbat, este luat prizonier și răscumpărat pentru o sumă mare de bani.",
  rezultat="Înfrângerea revoltei; moartea lui Litovoi",
  teritoriu="da",
  observatii="Locația exactă a bătăliei nu este cunoscută.",
  sursa="batalii.csv — sec. XIII d.Hr., pct. 2"),
 dict(
  titlu="Revoltele sașilor și secuilor (ex. revolta lui Gylul, 1277)",
  tip="Revoltă",
  data_start="c. 1277", data_end="c. 1290", an_start=1277, an_end=1290,
  secol="sec. XIII d.Hr.", secol_n=13,
  locatie="Transilvania: Alba Iulia și zonele colonizate (sași, secui)",
  zona_aprox=1, judet="Alba / Sibiu", regiune="Transilvania",
  lat=46.0, lng=24.0,
  participanti="Sași (conduși de Gylul), secui vs. voievodatul Transilvaniei și episcopia de Alba Iulia",
  descriere="Coloniștii sași și secui, așezați de Coroana Maghiară pentru a apăra granițele, se răscoală în repetate rânduri împotriva abuzurilor voievozilor Transilvaniei sau ale episcopiei de Alba Iulia. Un exemplu notabil: revolta sașilor conduși de Gylul din 1277, care ard catedrala din Alba Iulia.",
  rezultat="Reprimarea revoltelor; consolidarea treptată a autonomiei sașilor/secuilor",
  teritoriu="da",
  observatii="Eveniment tip, pe mai multe episoade.",
  sursa="batalii.csv — sec. XIII d.Hr., pct. 2"),
 dict(
  titlu="A doua invazie mongolă (1285) și bătălia de lângă Bistrița",
  tip="Invazie / bătălie",
  data_start="1285", data_end="1285", an_start=1285, an_end=1285,
  secol="sec. XIII d.Hr.", secol_n=13,
  locatie="Transilvania (Bistrița) și spațiul extracarpatic",
  zona_aprox=1, judet="Bistrița-Năsăud", regiune="Transilvania",
  lat=47.13, lng=24.49,
  participanti="Hoarda de Aur vs. Regatul Ungariei (armate maghiare și formațiuni locale)",
  descriere="După marea invazie, Hoarda de Aur continuă să atace regiunea. Invazia din 1285, cunoscută drept „a doua invazie mongolă”, lovește din nou Transilvania și spațiul extracarpatic. De data aceasta armatele maghiare și formațiunile locale sunt mai bine pregătite, iar mongolii sunt învinși în mai multe bătălii (cum ar fi cea de lângă Bistrița) și alungați.",
  rezultat="Respigerea celei de-a doua invazii mongole",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XIII d.Hr., pct. 3"),
 dict(
  titlu="Dominația militară a lui Nogai Han în Dobrogea",
  tip="Ocupație / dominație militară",
  data_start="c. 1271", data_end="c. 1299", an_start=1271, an_end=1299,
  secol="sec. XIII d.Hr.", secol_n=13,
  locatie="Dunărea de Jos: cartierul general probabil la Isaccea (jud. Tulcea)",
  zona_aprox=1, judet="Tulcea", regiune="Dobrogea",
  lat=45.27, lng=28.46,
  participanti="Hoarda de Aur (Nogai Han) vs. Imperiul Bizantin, Țaratul Bulgar și formațiunile locale",
  descriere="În a doua jumătate a secolului XIII, liderul tătar Nogai Han își stabilește cartierul general în zona Dunării de Jos (probabil la Isaccea), controlând militar și politic întreaga regiune și transformând Dobrogea într-o bază de operațiuni militare. Regiunea devine un teatru de război permanent între Hoarda de Aur, Bizanț și Bulgaria.",
  rezultat="Control tătăresc temporar asupra Dobrogei și Dunării de Jos",
  teritoriu="da",
  observatii="Eveniment de dominație, fără bătălii nominale în sursă.",
  sursa="batalii.csv — sec. XIII d.Hr., pct. 4"),
 dict(
  titlu="Bătălia de la Posada",
  tip="Bătălie",
  data_start="1330-11-09", data_end="1330-11-12", an_start=1330, an_end=1330,
  secol="sec. XIV d.Hr.", secol_n=14,
  locatie="Defileul/trecătoarea dintre Oltenia și Transilvania (zona Posada — Lainici/Novaci; identificare disputată)",
  zona_aprox=1, judet="Gorj / Vâlcea", regiune="Oltenia / Transilvania",
  lat=45.20, lng=23.40,
  participanti="Țara Românească (Basarab I) vs. Regatul Ungariei (Carol Robert de Anjou)",
  descriere="Oastea Țării Românești condusă de Basarab I îi surprinde și învinge armata maghiară a lui Carol Robert de Anjou, într-o trecătoare carpatică, în 9–12 noiembrie 1330. Victoria asigură independența statului muntean și reprezintă una dintre bătăliile fondatoare ale istoriei României.",
  rezultat="Victorie decisivă a Țării Românești; consolidarea independenței",
  teritoriu="da",
  observatii="Localizarea exactă a locului bătăliei este disputată (Posada, în zona Lainici–Novaci).",
  sursa="batalii.csv — sec. XIV d.Hr."),
 dict(
  titlu="Bătălia de la Rovine",
  tip="Bătălie",
  data_start="1394", data_end="1395", an_start=1394, an_end=1395,
  secol="sec. XIV d.Hr.", secol_n=14,
  locatie="Oltenia, zona Rovine (lângă Craiova/Târgu Jiu — identificare disputată)",
  zona_aprox=1, judet="Gorj / Dolj", regiune="Oltenia",
  lat=44.70, lng=23.60,
  participanti="Țara Românească (Mircea cel Bătrân) vs. Imperiul Otoman (Baiazid I)",
  descriere="Domnitorul Mircea cel Bătrân oprește ofensiva trupelor otomane conduse de Baiazid I pe teritoriul Țării Românești. Bătălia (datată 1394 sau 1395) este una dintre cele mai cunoscute confruntări antiotomane ale epocii, cu ecou literar („Balada” lui Cezar Bolliac și textul din legenda lui Tudor Vladimirescu).",
  rezultat="Retragerea otomană; menținerea rezistenței Țării Românești",
  teritoriu="da",
  observatii="Datarea exactă (1394/1395) este disputată; localizarea Rovine lor este controversată.",
  sursa="batalii.csv — sec. XIV d.Hr."),
 dict(
  titlu="Cruciada de la Nicopole (context — în afara teritoriului României)",
  tip="Cruciadă / bătălie (context)",
  data_start="1396", data_end="1396", an_start=1396, an_end=1396,
  secol="sec. XIV d.Hr.", secol_n=14,
  locatie="Nicopole (azi Nikopol, Bulgaria) — în afara teritoriului actual al României",
  zona_aprox=1, judet="—", regiune="—",
  lat=43.70, lng=24.90,
  participanti="Coaliția cruciată (inclusiv oastea lui Mircea cel Bătrân) vs. Imperiul Otoman (Baiazid I)",
  descriere="Oastea lui Mircea cel Bătrân sprijină coaliția cruciată antiotomană într-o luptă purtată la sud de Dunăre, cu ecouri directe asupra spațiului românesc. Cruciada se încheie cu o înfrângere severă a creștinilor.",
  rezultat="Înfrângerea cruciaților; consecințe negative pentru statele române",
  teritoriu="nu",
  observatii="Inclus ca eveniment de context regional cu participare românească.",
  sursa="batalii.csv — sec. XIV d.Hr."),
 dict(
  titlu="Campaniile antiotomane ale lui Iancu de Hunedoara",
  tip="Campanii militare",
  data_start="1440", data_end="1448", an_start=1440, an_end=1448,
  secol="sec. XV d.Hr.", secol_n=15,
  locatie="Transilvania și campaniile la sud de Dunăre",
  zona_aprox=1, judet="—", regiune="Transilvania / Balcani",
  lat=45.8, lng=23.0,
  participanti="Regatul Ungariei (Iancu de Hunedoara, voievod al Transilvaniei) vs. Imperiul Otoman",
  descriere="Voievodul Transilvaniei organizează lupte antiotomane la sudul Dunării și pe teritoriul românesc, culminând cu marile campanii și înfrângerile de la Varna (1444) și a doua bătălie de la Kosovo Polje (1448). Eforturile sale au contribuit la întărirea apărării antiotomane a zonei.",
  rezultat="Campanii glorioase, dar cu înfrângeri decisive în Balcani",
  teritoriu="da",
  observatii="Bătăliile majore (Varna, Kosovo) au avut loc în afara teritoriului actual al României.",
  sursa="batalii.csv — sec. XV d.Hr."),
 dict(
  titlu="Atacul de noapte de la Târgoviște",
  tip="Atac surpriză / rezistență",
  data_start="1462-06", data_end="1462-06", an_start=1462, an_end=1462,
  secol="sec. XV d.Hr.", secol_n=15,
  locatie="Târgoviște și zonele învecinate (județul Dâmbovița)",
  zona_aprox=1, judet="Dâmbovița", regiune="Țara Românească",
  lat=44.92, lng=25.46,
  participanti="Țara Românească (Vlad Țepeș) vs. Imperiul Otoman (Mehmed al II-lea)",
  descriere="Vlad Țepeș conduce o rezistență de hărțuire împotriva sultanului Mehmed al II-lea, care invadase Țara Românească după refuzul plății tributului. Atacul surpriză din iunie 1462 („atacul de noapte”) îl obligă pe sultan să se retragă.",
  rezultat="Retragerea sultanului; menținerea independenței de facto",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XV d.Hr."),
 dict(
  titlu="Bătălia de la Baia",
  tip="Bătălie",
  data_start="1467-12", data_end="1467-12", an_start=1467, an_end=1467,
  secol="sec. XV d.Hr.", secol_n=15,
  locatie="Baia (județul Suceava)",
  zona_aprox=0, judet="Suceava", regiune="Moldova",
  lat=47.42, lng=26.19,
  participanti="Moldova (Ștefan cel Mare) vs. Regatul Ungariei (Matei Corvin)",
  descriere="Ștefan cel Mare respinge o expediție a regelui Ungariei, Matei Corvin, decis să supună Moldova. În bătălia de la Baia, armata moldoveană îl învinge pe regele ungur, care este rănit și se retrage.",
  rezultat="Victorie moldoveană; respingerea expediției ungare",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XV d.Hr."),
 dict(
  titlu="Bătălia de la Vaslui (Podul Înalt)",
  tip="Bătălie",
  data_start="1475-01-10", data_end="1475-01-10", an_start=1475, an_end=1475,
  secol="sec. XV d.Hr.", secol_n=15,
  locatie="Podul Înalt, la sud-est de Vaslui (județul Vaslui)",
  zona_aprox=1, judet="Vaslui", regiune="Moldova",
  lat=46.63, lng=27.75,
  participanti="Moldova (Ștefan cel Mare) vs. Imperiul Otoman (Suleiman Pașa, armata Rumeliei)",
  descriere="Ștefan cel Mare obține o victorie strălucită împotriva unei armate otomane net superioare numeric, conduse de Suleiman Pașa, folosind terenul mlăștinos și tactici de ambuscadă. Victoria de la Vaslui a avut un ecou european major.",
  rezultat="Victorie moldoveană decisivă",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XV d.Hr."),
 dict(
  titlu="Bătălia de la Războieni / Valea Albă",
  tip="Bătălie",
  data_start="1476-07-26", data_end="1476-07-26", an_start=1476, an_end=1476,
  secol="sec. XV d.Hr.", secol_n=15,
  locatie="Războieni / Valea Albă (județul Neamț)",
  zona_aprox=1, judet="Neamț", regiune="Moldova",
  lat=47.078, lng=26.560,
  participanti="Moldova (Ștefan cel Mare) vs. Imperiul Otoman (Mehmed al II-lea)",
  descriere="Oastea Moldovei este înfrântă de sultanul Mehmed al II-lea, care invadase Moldova cu o armată uriașă. Cu toate acestea, otomanii nu pot cuceri țara datorită rezistenței din cetăți și a tacticii de hărțuire, retrăgându-se în cele din urmă.",
  rezultat="Înfrângere militară tactică, dar victorie strategică a Moldovei",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XV d.Hr."),
]
