# -*- coding: utf-8 -*-
"""Partea 6 - Sec. XVI - XX d.Hr. (epoca modernă și contemporană)"""
EVENTS = [
 dict(
  titlu="Războaiele lui Radu de la Afumați (1522–1525)",
  tip="Războaie / campanii",
  data_start="1522", data_end="1525", an_start=1522, an_end=1525,
  secol="sec. XVI d.Hr.", secol_n=16,
  locatie="Țara Românească (bătălii la Ștefănești, Gubavi, București)",
  zona_aprox=1, judet="Argeș / Giurgiu / Ilfov", regiune="Țara Românească",
  lat=44.9, lng=25.0,
  participanti="Țara Românească (Radu de la Afumați) vs. Imperiul Otoman și pretendenți sprijiniți de otomani",
  descriere="După moartea lui Neagoe Basarab, Țara Românească trece printr-o criză succesorală profundă. Radu de la Afumați poartă circa 20 de bătălii împotriva otomanilor și a pretendenților sprijiniți de aceștia, reușind temporar să împiedice transformarea țării în pașalâc turcesc.",
  rezultat="Menținerea autonomiei, dar cu tribut și instabilitate cronică",
  teritoriu="da",
  observatii="Inclus ca campanie (bătăliile individuale nu sunt detaliate în sursă).",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 3"),
 dict(
  titlu="Bătălia de la Mohács (context — în afara teritoriului României)",
  tip="Bătălie (context regional)",
  data_start="1526-08-29", data_end="1526-08-29", an_start=1526, an_end=1526,
  secol="sec. XVI d.Hr.", secol_n=16,
  locatie="Mohács (Ungaria) — în afara teritoriului actual al României",
  zona_aprox=1, judet="—", regiune="—",
  lat=45.99, lng=18.70,
  participanti="Regatul Ungariei vs. Imperiul Otoman (Soliman Magnificul)",
  descriere="Bătălia s-a dat pe teritoriul Ungariei de astăzi, dar prăbușirea Regatului Ungar a dus direct la transformarea Transilvaniei în principat autonom sub suzeranitate otomană (1541), generând conflicte interne între facțiunile nobiliare pro-habsburgice și pro-otomane pe tot parcursul secolului.",
  rezultat="Căderea Regatului Ungariei medievale; autonomie otomană pentru Transilvania",
  teritoriu="nu",
  observatii="Inclus ca eveniment de context regional.",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 5"),
 dict(
  titlu="Bătălia de la Feldioara",
  tip="Bătălie / intervenție militară",
  data_start="1529-06-22", data_end="1529-06-22", an_start=1529, an_end=1529,
  secol="sec. XVI d.Hr.", secol_n=16,
  locatie="Feldioara (județul Brașov)",
  zona_aprox=0, judet="Brașov", regiune="Transilvania",
  lat=45.82, lng=25.60,
  participanti="Moldova (Petru Rareș) și Regatul Ungariei de Est (Ioan Zápolya) vs. adepții lui Ferdinand de Habsburg",
  descriere="Petru Rareș intervine militar în Transilvania în sprijinul regelui Ioan Zápolya și obține o victorie categorică împotriva adepților lui Ferdinand de Habsburg, consolidând influența moldovenească în regiune.",
  rezultat="Victorie categorică a lui Petru Rareș și a lui Zápolya",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 2"),
 dict(
  titlu="Invazia otomană din 1538 în Moldova",
  tip="Invazie",
  data_start="1538", data_end="1538", an_start=1538, an_end=1538,
  secol="sec. XVI d.Hr.", secol_n=16,
  locatie="Moldova: Suceava (județul Suceava)",
  zona_aprox=1, judet="Suceava", regiune="Moldova",
  lat=47.65, lng=26.25,
  participanti="Imperiul Otoman (Soliman Magnificul) vs. Moldova (Petru Rareș)",
  descriere="Sultanul Soliman Magnificul organizează o campanie masivă împotriva Moldovei pentru a-l pedepsi pe Petru Rareș. Din cauza trădării marii boierimi, domnitorul este nevoit să fugă în Transilvania, iar Suceava este ocupată fără luptă.",
  rezultat="Ocuparea Moldovei; dețronarea lui Petru Rareș",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 2"),
 dict(
  titlu="Războaiele lui Ioan Vodă cel Viteaz — Bătălia de la Jiliște",
  tip="Bătălie",
  data_start="1574-04", data_end="1574-04", an_start=1574, an_end=1574,
  secol="sec. XVI d.Hr.", secol_n=16,
  locatie="Jiliște — sud-estul Moldovei, zona Prutului (locație disputată)",
  zona_aprox=1, judet="Galați / Vaslui", regiune="Moldova",
  lat=45.95, lng=28.00,
  participanti="Moldova (Ioan Vodă cel Viteaz) vs. armata otomano-munteană (pentru Petru Șchiopul)",
  descriere="Ioan Vodă cel Viteaz refuză să dubleze tributul cerut de Poartă și pornește o campanie fulgerătoare. În aprilie 1574 surprinde și zdrobește o armată turco-munteană venită să-l instaleze pe Petru Șchiopul pe tronul Moldovei.",
  rezultat="Victorie moldoveană surprinzătoare",
  teritoriu="da",
  observatii="Localizarea exactă a bătăliei de la Jiliște este disputată.",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 4"),
 dict(
  titlu="Bătălia de la Iezerul Cahulului",
  tip="Bătălie",
  data_start="1574-06", data_end="1574-06", an_start=1574, an_end=1574,
  secol="sec. XVI d.Hr.", secol_n=16,
  locatie="Iezerul Cahulului, pe Prut (azi în Republica Moldova)",
  zona_aprox=1, judet="—", regiune="Moldova (sud) / Basarabia",
  lat=45.91, lng=28.19,
  participanti="Moldova (Ioan Vodă cel Viteaz) vs. Imperiul Otoman (cu sprijinul muntean)",
  descriere="Din cauza lipsei de apă și a trădării pârcălabului Ieremia Golia, armata moldoveană este încercuită. Deși moldovenii luptă eroic, sunt înfrânți, iar Ioan Vodă este executat de otomani.",
  rezultat="Înfrângere moldoveană; execuția lui Ioan Vodă",
  teritoriu="partial",
  observatii="Zona se află în afara granițelor actuale ale României (Republica Moldova).",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 4"),
 dict(
  titlu="Bătălia de la Călugăreni",
  tip="Bătălie",
  data_start="1595-08-23", data_end="1595-08-23", an_start=1595, an_end=1595,
  secol="sec. XVI d.Hr.", secol_n=16,
  locatie="Călugăreni (județul Giurgiu), râul Neajlov",
  zona_aprox=0, judet="Giurgiu", regiune="Țara Românească",
  lat=44.18, lng=26.04,
  participanti="Țara Românească (Mihai Viteazul) vs. Imperiul Otoman (Sinan Pașa)",
  descriere="Una dintre cele mai faimoase confruntări ale epocii: armata munteană condusă de Mihai Viteazul obține o victorie tactică importantă împotriva unei armate otomane mult superioare numeric, conduse de Sinan Pașa, folosind terenul mlăștinos de la Călugăreni.",
  rezultat="Victorie tactică a lui Mihai Viteazul (retragere strategică ulterioară)",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Giurgiu (1595)",
  tip="Bătălie",
  data_start="1595-10", data_end="1595-10", an_start=1595, an_end=1595,
  secol="sec. XVI d.Hr.", secol_n=16,
  locatie="Giurgiu (județul Giurgiu)",
  zona_aprox=0, judet="Giurgiu", regiune="Țara Românească",
  lat=43.90, lng=25.97,
  participanti="Forțele aliate româno-transilvănene (Mihai Viteazul, Sigismund Báthory) vs. Imperiul Otoman (Sinan Pașa)",
  descriere="Forțele aliate ale românilor și transilvănenilor, sub comanda lui Mihai Viteazul și a lui Sigismund Báthory, zdrobesc ariergarda oastei lui Sinan Pașa care se retrăgea peste Dunăre.",
  rezultat="Victorie aliată; distrugerea ariergardei otomane",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Șelimbăr",
  tip="Bătălie",
  data_start="1599-10-28", data_end="1599-10-28", an_start=1599, an_end=1599,
  secol="sec. XVI d.Hr.", secol_n=16,
  locatie="Șelimbăr (județul Sibiu)",
  zona_aprox=0, judet="Sibiu", regiune="Transilvania",
  lat=45.77, lng=24.20,
  participanti="Țara Românească (Mihai Viteazul) vs. Transilvania (cardinalul Andrei Báthory)",
  descriere="Mihai Viteazul învinge armata transilvăneană condusă de cardinalul Andrei Báthory, victorie care îi deschide calea către Alba Iulia și preluarea controlului asupra Transilvaniei.",
  rezultat="Victorie a lui Mihai Viteazul; intrarea în Alba Iulia",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Mirăslău",
  tip="Bătălie",
  data_start="1600-09-18", data_end="1600-09-18", an_start=1600, an_end=1600,
  secol="sec. XVI/XVII d.Hr.", secol_n=16,
  locatie="Mirăslău (județul Alba)",
  zona_aprox=0, judet="Alba", regiune="Transilvania",
  lat=46.34, lng=23.68,
  participanti="Țara Românească/Transilvania (Mihai Viteazul) vs. nobilii maghiari răsculați și trupele imperiale habsburgice (Giorgio Basta)",
  descriere="Mihai Viteazul este înfrânt de o coaliție formată din nobilii maghiari răsculați și trupele imperiale habsburgice conduse de generalul Giorgio Basta, ceea ce provoacă prăbușirea primei sale domnii în Transilvania.",
  rezultat="Înfrângerea lui Mihai Viteazul; retragerea sa din Transilvania",
  teritoriu="da",
  observatii="Sursa îl menționează și la sec. XVII d.Hr. (recapitulare).",
  sursa="batalii.csv — sec. XVI d.Hr., pct. 1; sec. XVII d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Bucov",
  tip="Bătălie",
  data_start="1600-10", data_end="1600-10", an_start=1600, an_end=1600,
  secol="sec. XVI/XVII d.Hr.", secol_n=16,
  locatie="Bucov (județul Prahova), Muntenia",
  zona_aprox=0, judet="Prahova", regiune="Țara Românească",
  lat=44.97, lng=26.08,
  participanti="Polonia-Lituania (Jan Zamoyski), în sprijinul lui Simion Movilă vs. Țara Românească (Mihai Viteazul)",
  descriere="Polonezii conduși de Jan Zamoyski îl înving pe Mihai în Muntenia, impunându-l pe tron pe Simion Movilă. Bătălia marchează pierderea temporară a Țării Românești de către Mihai.",
  rezultat="Înfrângerea lui Mihai Viteazul; instalarea lui Simion Movilă",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Guruslău",
  tip="Bătălie",
  data_start="1601-08-03", data_end="1601-08-03", an_start=1601, an_end=1601,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Guruslău (județul Sălaj)",
  zona_aprox=0, judet="Sălaj", regiune="Transilvania",
  lat=47.23, lng=23.02,
  participanti="Mihai Viteazul și generalul Giorgio Basta (Imperiul Habsburgic) vs. Sigismund Báthory",
  descriere="Mihai Viteazul, aliat din nou cu generalul Basta, îl învinge pe Sigismund Báthory, restabilind controlul imperial asupra Transilvaniei cu puțin timp înainte de a fi asasinat.",
  rezultat="Victorie imperială; scurt timp după, asasinarea lui Mihai Viteazul",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Țuțora (1620)",
  tip="Bătălie",
  data_start="1620-09", data_end="1620-09", an_start=1620, an_end=1620,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Țuțora, pe Prut, lângă Iași (județul Iași)",
  zona_aprox=1, judet="Iași", regiune="Moldova",
  lat=46.98, lng=27.87,
  participanti="Polonia-Lituania și Moldova (suzeranitate otomană) vs. Imperiul Otoman și tătari",
  descriere="Datorită poziției geografice, Moldova devine teatru de război în confruntările dintre polonezi și turci. Armata poloneză, care susținea Moldova, este masacrată de otomani și tătari pe malul Prutului, lângă Iași.",
  rezultat="Masacrarea armatei poloneze; victorie otomană",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 4"),
 dict(
  titlu="Bătălia de la Hotin (1621)",
  tip="Bătălie",
  data_start="1621-09", data_end="1621-10", an_start=1621, an_end=1621,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Hotin (azi în Ucraina, la granița istorică a Moldovei)",
  zona_aprox=1, judet="—", regiune="—",
  lat=48.51, lng=26.49,
  participanti="Polonia-Lituania și cazaci vs. Imperiul Otoman (sultanul Osman al II-lea)",
  descriere="O mare bătălie de poziție la granița Moldovei, în care polonezii și cazacii opresc avansul armatei sultanului Osman al II-lea, evitând cucerirea zonei.",
  rezultat="Încheierea războiului prin tratat; menținerea status quo-ului",
  teritoriu="nu",
  observatii="Hotinul este azi în Ucraina; inclus ca eveniment de la granița istorică a Moldovei.",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 4"),
 dict(
  titlu="Bătălia de la Focșani (1637)",
  tip="Bătălie",
  data_start="1637", data_end="1637", an_start=1637, an_end=1637,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Focșani (județul Vrancea), frontiera moldo-munteană",
  zona_aprox=0, judet="Vrancea", regiune="Moldova / Țara Românească",
  lat=45.70, lng=27.18,
  participanti="Moldova (Vasile Lupu) vs. Țara Românească (Matei Basarab)",
  descriere="Rivalitatea dintre domnitorul Moldovei, Vasile Lupu, și cel al Țării Românești, Matei Basarab, duce la mai multe ciocniri militare violente. Bătălia de la Focșani este prima confruntare directă între armatele celor doi domnitori.",
  rezultat="Prima confruntare a războiului moldo-muntean",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 2"),
 dict(
  titlu="Bătălia de la Ojogeni",
  tip="Bătălie",
  data_start="1639", data_end="1639", an_start=1639, an_end=1639,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Ojogeni (județul Gorj) — identificare disputată",
  zona_aprox=1, judet="Gorj", regiune="Țara Românească",
  lat=45.12, lng=23.28,
  participanti="Moldova (Vasile Lupu) vs. Țara Românească (Matei Basarab)",
  descriere="Vasile Lupu invadează Țara Românească, dar este înfrânt decisiv de Matei Basarab în bătălia de la Ojogeni, una dintre cele mai sângeroase confruntări ale rivalității celor doi domnitori.",
  rezultat="Înfrângere decisivă a lui Vasile Lupu",
  teritoriu="da",
  observatii="Localizarea exactă a bătăliei este disputată.",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 2"),
 dict(
  titlu="Bătălia de la Finta",
  tip="Bătălie",
  data_start="1653-05-27", data_end="1653-05-27", an_start=1653, an_end=1653,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Finta (județul Dâmbovița)",
  zona_aprox=0, judet="Dâmbovița", regiune="Țara Românească",
  lat=44.80, lng=25.78,
  participanti="Țara Românească (Matei Basarab) și transilvăneni vs. Moldova (Vasile Lupu) cu cazaci (Timuș Hmelnițki)",
  descriere="Vasile Lupu, sprijinit de cazacii ginerelui său Timuș Hmelnițki, atacă din nou Muntenia. Matei Basarab obține o victorie zdrobitoare, conflictul marcând sfârșitul domniei lui Vasile Lupu.",
  rezultat="Victorie zdrobitoare a lui Matei Basarab; căderea lui Vasile Lupu",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 2"),
 dict(
  titlu="Campania otomană de pedepsire a Transilvaniei și Bătălia de la Gilău",
  tip="Campanie / bătălie",
  data_start="1657", data_end="1662", an_start=1657, an_end=1662,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Transilvania: Gilău (județul Cluj), Oradea, Crișana",
  zona_aprox=1, judet="Cluj / Bihor", regiune="Transilvania / Crișana",
  lat=46.75, lng=23.38,
  participanti="Imperiul Otoman și tătari vs. Principatul Transilvaniei (Gheorghe Rákóczi al II-lea)",
  descriere="Principele Transilvaniei Gheorghe Rákóczi al II-lea declanșează o campanie militară neautorizată în Polonia, provocând mânia Porții Otomane. Transilvania este devastată de expediții de pedepsire otomane și tătare; la Gilău (1660), Rákóczi al II-lea este rănit mortal. Otomanii cuceresc cetatea Oradea și transformă Crișana în pașalâc turcesc.",
  rezultat="Devastarea Transilvaniei; cucerirea Oradei; pașalâc otoman în Crișana",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 3"),
 dict(
  titlu="Campaniile lui Jan Sobieski în Moldova",
  tip="Campanii / expediții",
  data_start="1680", data_end="1690", an_start=1680, an_end=1690,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Moldova: Suceava, Iași, Neamț (ocupare temporară)",
  zona_aprox=1, judet="Suceava / Iași / Neamț", regiune="Moldova",
  lat=47.2, lng=26.4,
  participanti="Polonia-Lituania (regele Jan Sobieski) vs. Imperiul Otoman și Moldova (suzeranitate otomană)",
  descriere="Polonezii organizează mai multe expediții militare în Moldova, ocupând temporar Suceava, Iașiul și Neamțul, în încercarea de a scoate principatul de sub influența otomană.",
  rezultat="Ocupații temporare, fără schimbarea suzeranității",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 4"),
 dict(
  titlu="Bătălia de la Sânmartin (1685)",
  tip="Bătălie",
  data_start="1685", data_end="1685", an_start=1685, an_end=1685,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Sânmartin (posibil județul Bihor, lângă Oradea — identificare disputată)",
  zona_aprox=1, judet="Bihor", regiune="Transilvania / Crișana",
  lat=46.99, lng=21.96,
  participanti="Imperiul Habsburgic vs. Imperiul Otoman / forțele curuților",
  descriere="În cadrul Marelui Război Turcesc (1683–1699), după eșecul asediului otoman asupra Vienei, Sfânta Alianță condusă de Habsburgi lansează o ofensivă puternică; luptele se desfășoară intens și pe teritoriul românesc. Bătălia de la Sânmartin (1685) este o confruntare pe teritoriul Transilvaniei între forțele imperiale și cele otomane/curuți.",
  rezultat="Avans habsburgic în Transilvania",
  teritoriu="da",
  observatii="Localizarea exactă a bătăliei este disputată.",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 5"),
 dict(
  titlu="Bătălia de la Zărnești (1690)",
  tip="Bătălie",
  data_start="1690-08-21", data_end="1690-08-21", an_start=1690, an_end=1690,
  secol="sec. XVII d.Hr.", secol_n=17,
  locatie="Zărnești (județul Brașov)",
  zona_aprox=0, judet="Brașov", regiune="Transilvania",
  lat=45.58, lng=25.34,
  participanti="Imperiul Otoman și curuți (Imre Thököly) vs. Imperiul Habsburgic",
  descriere="Bătălie majoră a Marelui Război Turcesc, purtată pe teritoriul Transilvaniei: forțele otomane și curuții (conduși de Imre Thököly) înving armata imperială habsburgică, dar controlul asupra Transilvaniei se schimbă definitiv prin tratatul de la Karlowitz (1699), care cedează oficial principatul Habsburgilor.",
  rezultat="Victorie otomană/curuți; totuși, Karlowitz (1699) aduce Transilvania sub Habsburgi",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVII d.Hr., pct. 5"),
 dict(
  titlu="Războiul Ruso-Turc (1710–1711) și Bătălia de la Stănilești",
  tip="Război / bătălie",
  data_start="1710", data_end="1711", an_start=1710, an_end=1711,
  secol="sec. XVIII d.Hr.", secol_n=18,
  locatie="Stănilești, pe Prut (județul Vaslui)",
  zona_aprox=1, judet="Vaslui", regiune="Moldova",
  lat=46.63, lng=28.14,
  participanti="Rusia (Petru cel Mare) și Moldova (Dimitrie Cantemir) vs. Imperiul Otoman și tătari",
  descriere="Domnitorul Moldovei, Dimitrie Cantemir, se aliază secret cu țarul Petru cel Mare (Tratatul de la Luțk), încercând să elibereze țara de suzeranitatea otomană. La Stănilești, pe Prut (iulie 1711), armatele moldo-ruse sunt încercuite și înfrânte de otomani. Cantemir se exilează în Rusia, iar Poarta introduce regimul fanariot în Moldova (1711) și apoi în Țara Românească (1716).",
  rezultat="Înfrângerea moldo-rusă; introducerea regimului fanariot",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVIII d.Hr., pct. 1"),
 dict(
  titlu="Războiul Austro-Turc (1716–1718)",
  tip="Război",
  data_start="1716", data_end="1718", an_start=1716, an_end=1718,
  secol="sec. XVIII d.Hr.", secol_n=18,
  locatie="Banat și Țara Românească",
  zona_aprox=1, judet="—", regiune="Banat / Țara Românească",
  lat=45.5, lng=22.0,
  participanti="Imperiul Habsburgic vs. Imperiul Otoman",
  descriere="Trupele habsburgice atacă fortărețele otomane și pătrund adânc în Banat și Țara Românească. Conflictul se încheie prin Pacea de la Passarowitz (1718), prin care Imperiul Habsburgic anexează Banatul și Oltenia (aceasta fiind retrocedată Țării Românești două decenii mai târziu).",
  rezultat="Anexarea Banatului și Olteniei de către Habsburgi",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVIII d.Hr., pct. 2"),
 dict(
  titlu="Războiul Ruso-Austro-Turc (1735–1739)",
  tip="Război",
  data_start="1735", data_end="1739", an_start=1735, an_end=1739,
  secol="sec. XVIII d.Hr.", secol_n=18,
  locatie="Moldova (Iași), Oltenia și Muntenia",
  zona_aprox=1, judet="—", regiune="Moldova / Oltenia / Muntenia",
  lat=46.7, lng=26.5,
  participanti="Rusia și Imperiul Habsburgic vs. Imperiul Otoman",
  descriere="Teritoriul Moldovei și al Țării Românești este din nou teatru de război: trupele rusești ocupă Iașiul, iar austriecii luptă pe teritoriul Olteniei și în Muntenia. Se încheie prin Pacea de la Belgrad (1739), prin care Austria pierde Oltenia, care revine sub stăpânirea domniei de la București (și indirect sub suzeranitate otomană).",
  rezultat="Revenirea Olteniei sub autoritatea Bucureștiului",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVIII d.Hr., pct. 3"),
 dict(
  titlu="Războiul Ruso-Turc (1768–1774) și ocupația Principatelor",
  tip="Război / ocupație",
  data_start="1768", data_end="1774", an_start=1768, an_end=1774,
  secol="sec. XVIII d.Hr.", secol_n=18,
  locatie="Moldova și Țara Românească (Bătăliile de la Larga și Cahul — azi Republica Moldova)",
  zona_aprox=1, judet="—", regiune="Moldova / Țara Românească",
  lat=46.3, lng=28.0,
  participanti="Imperiul Rus vs. Imperiul Otoman",
  descriere="Unul dintre cele mai distructive conflicte ale secolului pentru spațiul românesc: Moldova și Țara Românească sunt complet ocupate de armatele țariste, iar bătăliile importante de la Larga și Cahul se dau pe teritoriul basarabean de atunci. Pacea de la Kuciuk-Kainargi (1774) retrocedează formal Principatele otomanilor, dar Rusia obține dreptul de a interveni în protejarea creștinilor; în 1775 Austria anexează nordul Moldovei (Bucovina).",
  rezultat="Ocupație și distrugeri; dreptul rusesc de intervenție; anexarea Bucovinei",
  teritoriu="da",
  observatii="Bătăliile de la Larga și Cahul au avut loc în afara granițelor actuale ale României.",
  sursa="batalii.csv — sec. XVIII d.Hr., pct. 4"),
 dict(
  titlu="Războiul Ruso-Austro-Turc (1787–1792) și bătăliile de la Focșani și Râmnicu Sărat",
  tip="Război / bătălii",
  data_start="1787", data_end="1792", an_start=1787, an_end=1792,
  secol="sec. XVIII d.Hr.", secol_n=18,
  locatie="București, Iași, Focșani, Râmnicu Sărat",
  zona_aprox=1, judet="Ilfov / Iași / Vrancea / Buzău", regiune="Țara Românească / Moldova",
  lat=45.5, lng=27.0,
  participanti="Rusia și Imperiul Habsburgic vs. Imperiul Otoman",
  descriere="Alianța austro-rusă atacă Imperiul Otoman pe pământ românesc: Bucureștiul și Iașiul sunt ocupate militar de trupele aliate, iar generalul rus Suvorov obține victorii răsunătoare la Focșani (1789) și Râmnicu Sărat (1789). Războiul se încheie prin Pacea de la Șiștov (1791) cu Austria și Pacea de la Iași (1792) cu Rusia, când granița rusă ajunge pentru prima dată pe Nistru.",
  rezultat="Ocupație militară; granița rusă pe Nistru; restabilirea suzeranității otomane",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XVIII d.Hr., pct. 5"),
 dict(
  titlu="Războiul Ruso-Turc (1806–1812) și anexarea Basarabiei",
  tip="Război",
  data_start="1806", data_end="1812", an_start=1806, an_end=1812,
  secol="sec. XIX d.Hr.", secol_n=19,
  locatie="Moldova (dintre Prut și Nistru) și Țara Românească",
  zona_aprox=1, judet="—", regiune="Moldova",
  lat=47.0, lng=28.0,
  participanti="Imperiul Rus vs. Imperiul Otoman (principatele române ca teatru de război)",
  descriere="Spațiul românesc este teatru de operațiuni sau ocupat militar: războiul se încheie cu Pacea de la București, prin care Imperiul Rus anexează jumătatea de est a Moldovei — teritoriul dintre Prut și Nistru, numit ulterior Basarabia.",
  rezultat="Anexarea Basarabiei de către Imperiul Rus",
  teritoriu="da",
  observatii="Moștenirea teritorială a evenimentului privește și Republica Moldova de azi.",
  sursa="batalii.csv — sec. XIX d.Hr."),
 dict(
  titlu="Războiul Ruso-Turc (1828–1829) și ocuparea Principatelor",
  tip="Război / ocupație",
  data_start="1828", data_end="1829", an_start=1828, an_end=1829,
  secol="sec. XIX d.Hr.", secol_n=19,
  locatie="Principatele Române (Moldova și Țara Românească)",
  zona_aprox=1, judet="—", regiune="Moldova / Țara Românească",
  lat=46.5, lng=26.5,
  participanti="Imperiul Rus vs. Imperiul Otoman",
  descriere="Principatele sunt ocupate de armata țaristă. Tratatul de la Adrianopol aduce modificări economice și politice majore (instituirea Regulamentelor Organice) și retrocedează Țării Românești cetățile dunărene: Brăila, Giurgiu și Turnu.",
  rezultat="Ocupație rusească; Regulamentele Organice; recâștigarea cetăților dunărene",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XIX d.Hr."),
 dict(
  titlu="Războiul Crimeii — ocuparea Principatelor (1853–1856)",
  tip="Război / ocupații",
  data_start="1853", data_end="1856", an_start=1853, an_end=1856,
  secol="sec. XIX d.Hr.", secol_n=19,
  locatie="Principatele Române (Moldova și Țara Românească)",
  zona_aprox=1, judet="—", regiune="Moldova / Țara Românească",
  lat=46.5, lng=26.5,
  participanti="Imperiul Rus vs. Imperiul Otoman (cu ocupări austriece și otomane de siguranță)",
  descriere="Conflictul începe prin ocuparea Principatelor Române de către trupele rusești, urmată apoi de o ocupație austriacă și otomană de siguranță. Deși luptele mari se mută în Crimeea, teritoriul românesc este direct afectat de ocupații și rechiziții.",
  rezultat="Ocupații succesive; restrângerea influenței ruse în principate",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XIX d.Hr."),
 dict(
  titlu="Revoluția lui Tudor Vladimirescu (1821)",
  tip="Revoltă / război intern",
  data_start="1821", data_end="1821", an_start=1821, an_end=1821,
  secol="sec. XIX d.Hr.", secol_n=19,
  locatie="Țara Românească: Gorj, Oltenia, București",
  zona_aprox=1, judet="Gorj / Dolj / Ilfov", regiune="Țara Românească",
  lat=44.8, lng=23.5,
  participanti="Pandurii lui Tudor Vladimirescu și eteriștii (Alexandru Ipsilanti) vs. Imperiul Otoman",
  descriere="Mișcare socială și națională puternică în Țara Românească: se dau lupte între pandurii lui Tudor Vladimirescu, eteriștii (revoluționarii greci conduși de Alexandru Ipsilanti, care acționau tot pe teritoriu românesc) și armatele otomane venite să înăbușe revolta. Tudor Vladimirescu este în cele din urmă asasinat.",
  rezultat="Înăbușirea revoltei; sfârșitul lui Tudor Vladimirescu",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XIX d.Hr."),
 dict(
  titlu="Revoluția de la 1848–1849 din Transilvania (război civil)",
  tip="Revoluție / război civil",
  data_start="1848", data_end="1849", an_start=1848, an_end=1849,
  secol="sec. XIX d.Hr.", secol_n=19,
  locatie="Transilvania: Munții Apuseni și diverse localități transilvănene",
  zona_aprox=1, judet="—", regiune="Transilvania",
  lat=46.3, lng=23.0,
  participanti="Revoluționarii maghiari vs. românii transilvăneni (Avram Iancu, aliați temporar cu Casa de Habsburg)",
  descriere="Revoluția degenerază într-un război civil sângeros între revoluționarii maghiari (care doreau unirea Transilvaniei cu Ungaria) și românii transilvăneni conduși de Avram Iancu, care apărau drepturile naționale ale românilor. Confruntările armate au loc în Munții Apuseni și în diverse localități, până la intervenția trupelor țariste, care înfrâng armata maghiară.",
  rezultat="Înfrângerea armatei maghiare de către intervenția țaristă; urmări pentru națiunea română",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XIX d.Hr."),
 dict(
  titlu="Războiul de Independență (Russo-Turc 1877–1878)",
  tip="Război",
  data_start="1877-04", data_end="1878", an_start=1877, an_end=1878,
  secol="sec. XIX d.Hr.", secol_n=19,
  locatie="Trecerea Dunării (Zimnicea) și luptele din Bulgaria (Plevna, Grivița, Rahova, Vidin)",
  zona_aprox=1, judet="Teleorman", regiune="Țara Românească / Balcani",
  lat=43.65, lng=25.37,
  participanti="România (domnitorul Carol I) și Imperiul Rus vs. Imperiul Otoman",
  descriere="Armata rusă traversează România pentru a ataca Imperiul Otoman; România se alătură militar Rusiei, iar trupele conduse de Carol I au un rol decisiv în asediile de la Plevna, Grivița, Rahova și Vidin. Conflictul consfințește independența de stat a României.",
  rezultat="Independența României (1877–1878); recunoaștere internațională",
  teritoriu="partial",
  observatii="Luptele principale au avut loc în afara granițelor actuale (Bulgaria); trecerea Dunării și mobilizarea s-au desfășurat pe teritoriul românesc.",
  sursa="batalii.csv — sec. XIX d.Hr."),
 dict(
  titlu="Primul Război Mondial — Campania din 1916 (înfrângerea inițială)",
  tip="Campanie / război",
  data_start="1916-08-27", data_end="1916-12", an_start=1916, an_end=1916,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Transilvania, Muntenia, Dobrogea, Moldova (capitola de război: Iași)",
  zona_aprox=1, judet="—", regiune="România",
  lat=46.0, lng=26.0,
  participanti="România (Antanta) vs. Puterile Centrale (Imperiul German, Austro-Ungaria, Bulgaria)",
  descriere="După o ofensivă de scurtă durată în Transilvania, armata română este nevoită să se retragă din cauza atacului combinat al trupelor germane, austro-ungare și bulgare. Sudul țării, inclusiv capitala București, este ocupat de Puterile Centrale; regele, guvernul și armata se retrag în Moldova, Iașiul devenind capitală de război.",
  rezultat="Ocuparea sudului României; retragerea armatei în Moldova",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bătălia de la Turtucaia",
  tip="Bătălie",
  data_start="1916-09-02", data_end="1916-09-06", an_start=1916, an_end=1916,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Turtucaia (azi Tutrakan, Bulgaria) — pe malul drept al Dunării, în fața Dobrogei",
  zona_aprox=1, judet="—", regiune="Dobrogea (graniță)",
  lat=44.05, lng=26.62,
  participanti="România (garnizoana Turtucaia) vs. Bulgaria și Imperiul German",
  descriere="Înfrângere severă a trupelor române în fața armatei bulgaro-germane, care deschide drumul inamicului spre Dobrogea. Una dintre cele mai mari catastrofe militare ale românilor în Primul Război Mondial.",
  rezultat="Înfrângere românească; ocuparea Dobrogei",
  teritoriu="nu",
  observatii="Turtucaia este azi în Bulgaria, imediat la frontiera cu România.",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bătălia de pe Valea Jiului (1916)",
  tip="Bătălie",
  data_start="1916-10", data_end="1916-11", an_start=1916, an_end=1916,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Valea Jiului (județele Gorj/Hunedoara)",
  zona_aprox=1, judet="Gorj / Hunedoara", regiune="Oltenia",
  lat=45.35, lng=23.15,
  participanti="România vs. Imperiul German (armata lui Falkenhayn)",
  descriere="Confruntare violentă prin care s-a încercat, fără succes, oprirea înaintării Puterilor Centrale, venite dinspre Transilvania prin Valea Jiului, spre București.",
  rezultat="Succes german inițial; depășirea apărării române",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bătălia de pe Neajlov–Argeș (1916)",
  tip="Bătălie",
  data_start="1916-11", data_end="1916-12", an_start=1916, an_end=1916,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Zona râurilor Neajlov și Argeș, la sud de București",
  zona_aprox=1, judet="Giurgiu / Ilfov", regiune="Muntenia",
  lat=44.35, lng=25.75,
  participanti="România vs. Imperiul German (von Mackensen)",
  descriere="Ultima încercare majoră de a opri înaintarea Puterilor Centrale spre București; după această confruntare, capitala este ocupată.",
  rezultat="Înfrângere românească; ocuparea Bucureștiului",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bătălia de la Mărăști (1917)",
  tip="Bătălie / ofensivă",
  data_start="1917-07-22", data_end="1917-08-01", an_start=1917, an_end=1917,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Mărăști (județul Vrancea)",
  zona_aprox=0, judet="Vrancea", regiune="Moldova",
  lat=45.83, lng=26.77,
  participanti="România (generalul Alexandru Averescu) vs. Imperiul German și Austro-Ungaria",
  descriere="Ofensivă românească reușită, sub conducerea generalului Alexandru Averescu, prin care s-a obținut eliberarea mai multor localități și întărirea moralului armatei române reorganizate.",
  rezultat="Victorie românească; eliberarea unor localități",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bătălia de la Mărășești (1917)",
  tip="Bătălie",
  data_start="1917-08-06", data_end="1917-09-03", an_start=1917, an_end=1917,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Mărășești (județul Vrancea)",
  zona_aprox=0, judet="Vrancea", regiune="Moldova",
  lat=45.88, lng=27.23,
  participanti="România vs. Imperiul German (von Mackensen)",
  descriere="Cea mai mare bătălie de pe frontul românesc: armata română rezistă eroic atacului german, stabilizând frontul sub deviza „Pe aici nu se trece!”.",
  rezultat="Victorie defensivă românească; stabilizarea frontului",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bătălia de la Oituz (1917)",
  tip="Bătălie",
  data_start="1917-08-08", data_end="1917-08-20", an_start=1917, an_end=1917,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Valea Oituzului (județele Bacău/Covasna)",
  zona_aprox=1, judet="Bacău / Covasna", regiune="Moldova / Transilvania",
  lat=46.10, lng=26.43,
  participanti="România vs. Imperiul German și Austro-Ungaria",
  descriere="Desfășurată în paralel cu bătălia de la Mărășești, trupele române blochează încercarea inamicului de a pătrunde în valea Trotușului, în inima Moldovei.",
  rezultat="Victorie defensivă românească",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Al Doilea Război Mondial — Operațiunea Tidal Wave (bombardarea Ploieștiului)",
  tip="Bombardament aerian",
  data_start="1943-08-01", data_end="1943-08-01", an_start=1943, an_end=1943,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Ploiești (județul Prahova)",
  zona_aprox=0, judet="Prahova", regiune="Muntenia",
  lat=44.94, lng=26.02,
  participanti="SUA (USAAF) vs. România (apărarea antiaeriană) și Germania Nazistă (apărarea rafinăriilor)",
  descriere="Atac aerian masiv al aviației americane (USAAF) asupra rafinăriilor de petrol de la Ploiești — una dintre cele mai sângeroase și costisitoare misiuni aeriene pentru americani din întreg războiul.",
  rezultat="Distrugeri parțiale ale rafinăriilor, cu pierderi aeriene americane mari",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bombardamentele aliate asupra României (1943–1944)",
  tip="Bombardamente aeriene",
  data_start="1943", data_end="1944", an_start=1943, an_end=1944,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="București, Ploiești, Turnu Severin, Brașov",
  zona_aprox=1, judet="Ilfov / Prahova / Mehedinți / Brașov", regiune="România",
  lat=44.8, lng=25.4,
  participanti="Aliații (SUA — USAAF, Regatul Unit — RAF) vs. România și Germania Nazistă",
  descriere="Înainte de intrarea trupelor terestre, România este ținta unor intense atacuri aeriene americane și britanice, având ca scop distrugerea infrastructurii petroliere și feroviare. Orașe precum București (inclusiv atacul devastator din 4 aprilie 1944 asupra Gării de Nord), Ploiești, Turnu Severin și Brașov sunt bombardate sistematic.",
  rezultat="Distrugeri ale infrastructurii; victime civile numeroase",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Ofensiva Uman–Botoșani (1944)",
  tip="Ofensivă",
  data_start="1944-03", data_end="1944-04", an_start=1944, an_end=1944,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Nordul Moldovei: Botoșani, Dorohoi, Suceava",
  zona_aprox=1, judet="Botoșani / Suceava", regiune="Moldova",
  lat=47.8, lng=26.5,
  participanti="URSS (Armata Roșie) vs. România și Germania Nazistă",
  descriere="Ofensiva marchează intrarea trupelor sovietice pe teritoriul României: Frontul de Est ajunge în nordul Moldovei, iar sovieticii ocupă orașe precum Botoșani, Dorohoi și Suceava, stabilind linia frontului în nordul țării.",
  rezultat="Ocuparea nordului Moldovei de către Armata Roșie",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Prima Ofensivă Iași–Chișinău (1944) și bătălia de la Târgu Frumos",
  tip="Ofensivă / bătălie de blindate",
  data_start="1944-04-08", data_end="1944-06-06", an_start=1944, an_end=1944,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Moldova: Târgu Frumos, valea Siretului, Iași–Chișinău",
  zona_aprox=1, judet="Iași / Neamț", regiune="Moldova",
  lat=47.21, lng=26.99,
  participanti="URSS (Armata Roșie) vs. România și Germania Nazistă (generalul Hasso von Manteuffel)",
  descriere="Serie de lupte violente de uzură între trupele germano-române și cele sovietice. Bătălia de la Târgu Frumos este o confruntare de blindate de mare amploare, unde trupele germane și cele române reușesc temporar să oprească avansul tancurilor sovietice.",
  rezultat="Stoparea temporară a ofensivei sovietice",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="A Doua Ofensivă Iași–Chișinău (20–29 august 1944)",
  tip="Ofensivă strategică",
  data_start="1944-08-20", data_end="1944-08-29", an_start=1944, an_end=1944,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Moldova: Iași, Chișinău, frontul germano-român",
  zona_aprox=1, judet="Iași", regiune="Moldova",
  lat=47.1, lng=27.5,
  participanti="URSS (Armata Roșie) vs. România și Germania Nazistă",
  descriere="Operațiune strategică sovietică masivă care duce la prăbușirea completă a frontului germano-român din Moldova: Armata Roșie sparge rapid liniile defensive de la Iași și Chișinău. Prăbușirea militară accelerează lovitura de stat de la București din 23 august 1944.",
  rezultat="Prăbușirea frontului; lovitura de stat din 23 august 1944",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bătălia pentru București (august–septembrie 1944)",
  tip="Bătălie urbană",
  data_start="1944-08-24", data_end="1944-09", an_start=1944, an_end=1944,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="București",
  zona_aprox=1, judet="Ilfov", regiune="Muntenia",
  lat=44.43, lng=26.10,
  participanti="România (armata, după 23 august) vs. Germania Nazistă",
  descriere="După actul de la 23 august 1944, teritoriul României devine teatrul unor lupte intense între foștii aliați. Trupele române resping atacurile germane care încercau să ocupe Capitala și să instaureze un regim marionetă; până la sosirea sovieticilor, Bucureștiul este deja eliberat de armata română.",
  rezultat="Eliberarea Bucureștiului de către armata română",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Luptele de pe linia Dunării și din Dobrogea (1944)",
  tip="Lupte de retragere / blocare",
  data_start="1944-08", data_end="1944-09", an_start=1944, an_end=1944,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Dunărea de Jos și Dobrogea",
  zona_aprox=1, judet="Constanța / Tulcea / Călărași", regiune="Dobrogea",
  lat=44.4, lng=28.0,
  participanti="România și URSS vs. Germania Nazistă",
  descriere="Confruntări pentru blocarea retragerii trupelor germane din Balcani, desfășurate pe linia Dunării și în Dobrogea, ca parte a luptelor de după 23 august 1944.",
  rezultat="Blocarea și capturarea unor forțe germane care se retrăgeau",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bătălia de la Turda (1944)",
  tip="Bătălie de blindate",
  data_start="1944-09", data_end="1944-10", an_start=1944, an_end=1944,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Turda (județul Cluj)",
  zona_aprox=0, judet="Cluj", regiune="Transilvania",
  lat=46.57, lng=23.78,
  participanti="România și URSS vs. Germania Nazistă și Ungaria",
  descriere="Una dintre cele mai mari și mai grele bătălii de blindate de pe teritoriul actual al României: trupele ungaro-germane opun o rezistență dârză în fața forțelor româno-sovietice, în cadrul campaniei de eliberare a Transilvaniei de Nord.",
  rezultat="Cucerirea Turdei de către forțele româno-sovietice",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Bătălia de la Păuliș (1944)",
  tip="Bătălie defensivă",
  data_start="1944-09-14", data_end="1944-09-19", an_start=1944, an_end=1944,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Păuliș (județul Arad)",
  zona_aprox=0, judet="Arad", regiune="Banat",
  lat=46.12, lng=21.59,
  participanti="România (elevii Școlii de Subofițeri de Rezervă de la Radna) vs. Ungaria (armata horthystă)",
  descriere="Elevii școlii de subofițeri de rezervă de la Radna opresc o ofensivă puternică a trupelor ungare, într-una dintre cele mai eroice confruntări defensive ale campaniei din vestul României.",
  rezultat="Victorie defensivă românească împotriva forțelor superioare",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
 dict(
  titlu="Eliberarea Careiului și Satu Mare (25 octombrie 1944)",
  tip="Ofensivă / eliberare",
  data_start="1944-10", data_end="1944-10-25", an_start=1944, an_end=1944,
  secol="sec. XX d.Hr.", secol_n=20,
  locatie="Carei și Satu Mare",
  zona_aprox=1, judet="Satu Mare", regiune="Transilvania (nord-vest)",
  lat=47.79, lng=22.89,
  participanti="România și URSS vs. Germania Nazistă și Ungaria",
  descriere="Armata română, acționând împreună cu Armata Roșie, eliberează în 25 octombrie 1944 orașele Carei și Satu Mare, încheind eliberarea întregului teritoriu actual al României de sub ocupația trupelor Axei.",
  rezultat="Eliberarea completă a teritoriului României (25 oct. 1944)",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. XX d.Hr."),
]
