# -*- coding: utf-8 -*-
"""Partea 2 - Sec. III - I î.Hr."""
EVENTS = [
 dict(
  titlu="Campania lui Agatocle împotriva geților (prima campanie a lui Lysimah)",
  tip="Campanie",
  data_start="-300", data_end="-300", an_start=-300, an_end=-300,
  secol="sec. III î.Hr.", secol_n=-3,
  locatie="Câmpia din sudul României (Muntenia / Dobrogea)",
  zona_aprox=1, judet="—", regiune="Muntenia / Dobrogea",
  lat=44.5, lng=26.5,
  participanti="Regatul Macedoniei/Tracia (Agatocle, fiul lui Lysimah) vs. Regatul getic (Dromichaetes)",
  descriere="Lysimah trimite peste Dunăre o armată condusă de fiul său Agatocle pentru a supune geții. Armata lui Dromichaetes obține o victorie totală, iar Agatocle este luat prizonier, răscumpărat ulterior.",
  rezultat="Victorie getică totală; Agatocle prizonier",
  teritoriu="da",
  observatii="Localizarea exactă a confruntării nu este cunoscută.",
  sursa="batalii.csv — sec. III î.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Helis și capturarea lui Lysimah",
  tip="Bătălie / campanie",
  data_start="-292", data_end="-292", an_start=-292, an_end=-292,
  secol="sec. III î.Hr.", secol_n=-3,
  locatie="Stepele dobrogene sau muntene (cetatea getică Helis)",
  zona_aprox=1, judet="—", regiune="Dobrogea / Muntenia",
  lat=44.7, lng=27.2,
  participanti="Regatul getic (Dromichaetes) vs. Regatul Macedoniei/Tracia (Lysimah)",
  descriere="Lysimah conduce personal o expediție uriașă la nord de Dunăre, dar armata macedoneană este încercuită în stepele dobrogene sau muntene din lipsă de apă și hrană. Lysimah este capturat și dus la cetatea getică Helis; conflictul se încheie cu un tratat de pace celebru, prin care Dromichaetes îi redă libertatea macedoneanului în schimbul retrocedării cetăților dunărene.",
  rezultat="Pace în care Dromichaetes își impune condițiile; retrocedarea cetăților dunărene",
  teritoriu="da",
  observatii="Datare cca. 292 î.Hr.; locația Helis este disputată.",
  sursa="batalii.csv — sec. III î.Hr., pct. 1"),
 dict(
  titlu="Invazia și conflictele cu celții (galații)",
  tip="Invazie / războaie de uzură",
  data_start="c. -280", data_end="c. -250", an_start=-280, an_end=-250,
  secol="sec. III î.Hr.", secol_n=-3,
  locatie="Transilvania, Oltenia și Banat",
  zona_aprox=1, judet="—", regiune="Transilvania / Oltenia / Banat",
  lat=45.9, lng=22.8,
  participanti="Celți (scordisci, taurisci, anarți) vs. daci și geți locali",
  descriere="Triburile celtice migrează masiv spre Balcani, stabilindu-se și pe teritoriul României. În Transilvania se ciocnesc cu comunitățile dacice, cucerind parțial podișul, dar dacii rezistă în zonele montane, generând un conflict de uzură de decenii. În Oltenia și Banat, scordiscii poartă lupte grele cu geții din zonele de câmpie pentru controlul Dunării.",
  rezultat="Coabitare ulterioară; celții păstrează controlul parțial al podișului",
  teritoriu="da",
  observatii="Fără bătălii nominale; zonele sunt aproximative.",
  sursa="batalii.csv — sec. III î.Hr., pct. 2"),
 dict(
  titlu="Războiul pentru Tomis (Histria și Callatis vs. Byzantion)",
  tip="Război / conflict comercial",
  data_start="c. -260", data_end="c. -260", an_start=-260, an_end=-260,
  secol="sec. III î.Hr.", secol_n=-3,
  locatie="Tomis (Constanța), litoralul Mării Negre",
  zona_aprox=0, judet="Constanța", regiune="Dobrogea",
  lat=44.17, lng=28.65,
  participanti="Cetățile Callatis și Histria vs. Byzantion (sprijinit de flota ptolemeică a Egiptului)",
  descriere="Cetățile Callatis (Mangalia) și Histria se aliază și intră în conflict cu Byzantionul pentru controlul emporiului (pieței comerciale) de la Tomis. Histria și Callatis sunt înfrânte în urma intervenției flotei regelui ptolemeic din Egipt.",
  rezultat="Înfrângerea alianței Histria–Callatis; controlul bizantin/egiptean asupra emporiului",
  teritoriu="da",
  observatii="Datarea (c. 260 î.Hr.) este aproximativă.",
  sursa="batalii.csv — sec. III î.Hr., pct. 3"),
 dict(
  titlu="Protectoratele militare ale regilor geți asupra cetăților grecești",
  tip="Presiune militară / tribut",
  data_start="c. -260", data_end="c. -201", an_start=-260, an_end=-201,
  secol="sec. III î.Hr.", secol_n=-3,
  locatie="Cetățile grecești din Dobrogea (Histria, Tomis, Callatis)",
  zona_aprox=1, judet="Constanța", regiune="Dobrogea",
  lat=44.0, lng=28.5,
  participanti="Regi geți (Zalmodegikos, Rhemaxos) vs. cetăți grecești pontice",
  descriere="Regii geți din Dobrogea impun protectorate militare cetăților grecești, oferindu-le „apărare” împotriva altor barbari în schimbul unor sume de bani (tribut), acțiuni dublate adesea de demonstrații de forță militară.",
  rezultat="Suzeranitate getică de facto asupra cetăților grecești (tribut)",
  teritoriu="da",
  observatii="Eveniment tip, fără bătălii nominale.",
  sursa="batalii.csv — sec. III î.Hr., pct. 3"),
 dict(
  titlu="Conflictele cu bastarnii",
  tip="Invazie / conflicte teritoriale",
  data_start="c. -220", data_end="c. -201", an_start=-220, an_end=-201,
  secol="sec. III î.Hr.", secol_n=-3,
  locatie="Nordul Moldovei și Câmpia Română",
  zona_aprox=1, judet="—", regiune="Moldova / Muntenia",
  lat=46.6, lng=26.0,
  participanti="Bastarni (populație germanică sau celto-germanică) vs. triburi geto-dace",
  descriere="Spre sfârșitul secolului III î.Hr., bastarnii pătrund în nordul Moldovei și în Câmpia Română, intrând imediat în conflicte teritoriale sângeroase cu triburile geto-dace locale, pe care le împing treptat spre sud și vest.",
  rezultat="Deplasarea spre sud-vest a triburilor geto-dace",
  teritoriu="da",
  observatii="Eveniment tip; zona aproximativă.",
  sursa="batalii.csv — sec. III î.Hr., pct. 4"),
 dict(
  titlu="Războaiele regelui Oroles împotriva bastarnilor",
  tip="Război / campanie",
  data_start="c. -200", data_end="c. -150", an_start=-200, an_end=-150,
  secol="sec. II î.Hr.", secol_n=-2,
  locatie="Moldova (estul și nord-estul teritoriului actual)",
  zona_aprox=1, judet="—", regiune="Moldova",
  lat=47.0, lng=27.0,
  participanti="Regatul geto-dac (regele Oroles) vs. bastarni",
  descriere="Bastarnii migrează din nord și pătrund în estul și nord-estul teritoriului actual (zona Moldovei). Regele geto-dac Oroles se izbește militar de invadatori: potrivit lui Trogus Pompeius, dacii sunt învinși într-o primă fază, apoi, după ce regele îi pedepsește simbolic pe războinici, îi înving pe bastarni într-o bătălie decisivă.",
  rezultat="Respigerea bastarnilor și stabilizarea graniței de est",
  teritoriu="da",
  observatii="Datare convențională (începutul sec. II î.Hr.).",
  sursa="batalii.csv — sec. II î.Hr., pct. 1"),
 dict(
  titlu="Campaniile lui Rubobostes împotriva celților",
  tip="Războaie / campanii",
  data_start="c. -170", data_end="c. -120", an_start=-170, an_end=-120,
  secol="sec. II î.Hr.", secol_n=-2,
  locatie="Transilvania (vestul și nord-vestul României)",
  zona_aprox=1, judet="—", regiune="Transilvania",
  lat=46.5, lng=23.5,
  participanti="Uniunea de triburi dacă (Rubobostes) vs. triburi celtice (scordisci, taurisci)",
  descriere="În prima jumătate a secolului II î.Hr., vestul și nord-vestul României se aflau parțial sub influența triburilor celtice. Uniunea de triburi condusă de regele dac Rubobostes declanșează o serie de războaie împotriva celților; succesul militar oprește expansiunea celtică și crește puterea dacilor în Transilvania, fiind considerat un precursor al unificării lui Burebista.",
  rezultat="Înfrângerea celților; afirmarea puterii dacice în Transilvania",
  teritoriu="da",
  observatii="Datare aproximativă pe baza contextului arheologic.",
  sursa="batalii.csv — sec. II î.Hr., pct. 2"),
 dict(
  titlu="Incursiunile scordiscilor în Câmpia Română și Dobrogea",
  tip="Incursiuni de jaf / conflicte de frontieră",
  data_start="c. -200", data_end="c. -101", an_start=-200, an_end=-101,
  secol="sec. II î.Hr.", secol_n=-2,
  locatie="Câmpia Română, Dunărea de Jos și cetățile grecești pontice",
  zona_aprox=1, judet="—", regiune="Muntenia / Dobrogea",
  lat=44.3, lng=26.8,
  participanti="Scordisci (trib celtic, zona Belgradului) vs. geți și cetăți grecești pontice",
  descriere="Scordiscii atacă frecvent triburile de geți de-a lungul Dunării și cetățile grecești pontice. Geții sunt implicați constant în ciocniri de apărare și hărțuieli de frontieră pentru a-și proteja așezările fortificate (davele).",
  rezultat="Conflicte de uzură și jaf; menținerea controlului local asupra trecătorilor Dunării",
  teritoriu="da",
  observatii="Eveniment tip; zona aproximativă.",
  sursa="batalii.csv — sec. II î.Hr., pct. 3"),
 dict(
  titlu="Războiul lui Burebista împotriva celților (boii și tauriscii)",
  tip="Război / campanie",
  data_start="c. -60", data_end="c. -59", an_start=-60, an_end=-59,
  secol="sec. I î.Hr.", secol_n=-1,
  locatie="Vestul și nord-vestul teritoriului dacic (zona Tisei și vestul României)",
  zona_aprox=1, judet="—", regiune="Banat / Crișana / Transilvania (vest)",
  lat=45.9, lng=21.3,
  participanti="Regatul geto-dac (Burebista) vs. confederații celtice (boii, tauriscii)",
  descriere="În jurul anilor 60–59 î.Hr., Burebista atacă și zdrobește confederațiile celtice din vestul și nord-vestul teritoriului dacic. Celții sunt atât de crunt învinși încât teritoriul lor rămâne cunoscut în epocă drept „pustiul boic”.",
  rezultat="Victorie dacică decisivă; dispariția puterii celtice din regiune",
  teritoriu="da",
  observatii="Datare aproximativă (c. 60–59 î.Hr.).",
  sursa="batalii.csv — sec. I î.Hr., pct. 1"),
 dict(
  titlu="Campania lui Burebista împotriva bastarnilor și sciților",
  tip="Campanie",
  data_start="c. -60", data_end="c. -44", an_start=-60, an_end=-44,
  secol="sec. I î.Hr.", secol_n=-1,
  locatie="Estul României (Moldova) și peste Prut",
  zona_aprox=1, judet="—", regiune="Moldova",
  lat=47.2, lng=28.0,
  participanti="Regatul geto-dac (Burebista) vs. bastarni (germanici) și sciți (iranieni)",
  descriere="Burebista duce lupte în estul României (Moldova) și peste Prut pentru a securiza granița estică împotriva bastarnilor și sciților, populații germanice și iraniene.",
  rezultat="Securizarea graniței estice a regatului dacic",
  teritoriu="da",
  observatii="Zonă aproximativă; fără bătălii nominale în sursă.",
  sursa="batalii.csv — sec. I î.Hr., pct. 1"),
 dict(
  titlu="Cucerirea orașelor grecești pontice de către Burebista",
  tip="Campanie / cucerire",
  data_start="c. -55", data_end="c. -48", an_start=-55, an_end=-48,
  secol="sec. I î.Hr.", secol_n=-1,
  locatie="Dobrogea: Histria, Tomis (Constanța), Callatis (Mangalia), până la Apollonia",
  zona_aprox=0, judet="Constanța", regiune="Dobrogea",
  lat=44.1, lng=28.5,
  participanti="Regatul geto-dac (Burebista) vs. cetăți grecești pontice (sub influența Romei)",
  descriere="Burebista pornește o campanie fulgerătoare prin Dobrogea, asediind și cucerind rând pe rând coloniile grecești aliate sau aflate sub influența Romei: Histria, Tomis, Callatis, până la Apollonia. Histria este parțial distrusă în urma acestui conflict.",
  rezultat="Cucerirea cetăților grecești pontice; extinderea hegemoniei dacice",
  teritoriu="da",
  observatii="Datare aproximativă (55–48 î.Hr.).",
  sursa="batalii.csv — sec. I î.Hr., pct. 1"),
 dict(
  titlu="Implicarea lui Burebista în Războiul Civil Roman (context — nu pe teritoriul României)",
  tip="Implicare diplomatică / militară indirectă",
  data_start="-48", data_end="-48", an_start=-48, an_end=-48,
  secol="sec. I î.Hr.", secol_n=-1,
  locatie="În afara teritoriului actual al României (context: Pharsalus, Grecia)",
  zona_aprox=1, judet="—", regiune="—",
  lat=39.3, lng=22.4,
  participanti="Regatul geto-dac (Burebista, sprijin promis lui Pompei) vs. Iulius Caesar (Republica Romană)",
  descriere="În timpul războiului civil dintre Iulius Caesar și Pompei, Burebista îl sprijină pe Pompei, trimițând promisiuni de ajutor militar prin diplomatul Acornion din Dionysopolis. Pompei este învins la Pharsalus (48 î.Hr.), iar Caesar planifică o campanie de răzbunare și cucerire a Daciei, dar conflictul direct nu mai are loc pentru că ambii lideri sunt asasinați în anul 44 î.Hr.",
  rezultat="Nu a avut loc o confruntare pe teritoriul României; planul roman de cucerire este abandonat",
  teritoriu="nu",
  observatii="Inclus pentru contextul istoric complet; nu este un conflict pe teritoriul actual al României.",
  sursa="batalii.csv — sec. I î.Hr., pct. 2"),
 dict(
  titlu="Războaiele interne de succesiune după moartea lui Burebista",
  tip="Război civil / fragmentare",
  data_start="-44", data_end="c. -30", an_start=-44, an_end=-30,
  secol="sec. I î.Hr.", secol_n=-1,
  locatie="Teritoriul regatului dacic (fără localizare precisă)",
  zona_aprox=1, judet="—", regiune="Geto-Dacia",
  lat=45.5, lng=25.0,
  participanti="Regate dace rivale (regi-preoți ca Deceneu și Comosicus, lideri locali ca Dicames, Cotiso, Roles)",
  descriere="După asasinarea lui Burebista în 44 î.Hr., statul dac se destramă inițial în patru, apoi în cinci regate mai mici. Perioada este marcată de războaie interne de succesiune între diversele formațiuni statale dace, slăbind puterea centralizată.",
  rezultat="Fragmentarea regatului dac; slăbirea militară și politică",
  teritoriu="da",
  observatii="Zonă aproximativă; fără bătălii nominale.",
  sursa="batalii.csv — sec. I î.Hr., pct. 3"),
 dict(
  titlu="Războiul lui Marcus Licinius Crassus în Dobrogea",
  tip="Război / campanie",
  data_start="-29", data_end="-28", an_start=-29, an_end=-28,
  secol="sec. I î.Hr.", secol_n=-1,
  locatie="Dobrogea (cetățile lui Dapyx și Zyraxes — Genucla)",
  zona_aprox=1, judet="Constanța / Tulcea", regiune="Dobrogea",
  lat=44.4, lng=28.2,
  participanti="Republica Romană (Crassus) și geții lui Roles vs. geții lui Dapyx și Zyraxes",
  descriere="Generalul roman Crassus (nepotul triumvirului) intervine la Dunăre în sprijinul regelui get Roles, aflat în conflict cu Dapyx, alt șef get. Romanii asediază cetatea lui Dapyx și cuceresc ulterior și cetatea regelui Zyraxes (Genucla).",
  rezultat="Dobrogea intră sub controlul indirect al Romei",
  teritoriu="da",
  observatii="Localizarea cetăților este aproximativă.",
  sursa="batalii.csv — sec. I î.Hr., pct. 4"),
 dict(
  titlu="Incursiunile dacilor transdanubieni în Moesia",
  tip="Incursiuni de jaf / expediții de represalii",
  data_start="c. -30", data_end="c. -10", an_start=-30, an_end=-10,
  secol="sec. I î.Hr.", secol_n=-1,
  locatie="Dunărea de Jos (sudul Olteniei și Munteniei) și Moesia (sud de Dunăre)",
  zona_aprox=1, judet="—", regiune="Oltenia / Muntenia",
  lat=44.2, lng=24.5,
  participanti="Daci din interiorul arcului carpatic (uneori sub regele Cotiso) vs. Republica Romană (provincia Moesia)",
  descriere="Spre sfârșitul secolului I î.Hr., iarna, când Dunărea îngheață, triburile dace din interiorul arcului carpatic trec fluviul ca să prade provinciile romane din Balcani (Moesia), generând expediții romane de represalii pe teritoriul actual al Olteniei și Munteniei.",
  rezultat="Raiduri și represalii recurente; frontiera dunăreană rămâne tensionată",
  teritoriu="da",
  observatii="Eveniment tip; zona aproximativă.",
  sursa="batalii.csv — sec. I î.Hr., pct. 4"),
]
