# -*- coding: utf-8 -*-
"""Partea 1 - Antichitate (sec. VIII - I î.Hr.)
Sursa principală: batalii.csv (Excel utilizator). Data completată/standardizată din
istoriografia consacrată; coordonatele sunt aproximative.
Numele de bază ale câmpurilor sunt documentate în build_conflicts_db.py
"""
EVENTS = [
 dict(
  titlu="Incursiunile cimerienilor și ale pre-sciților",
  tip="Incursiuni / invazii nomade",
  data_start="c. -800", data_end="c. -701", an_start=-800, an_end=-701,
  secol="sec. VIII î.Hr.", secol_n=-8,
  locatie="Dobrogea, sudul Moldovei și estul Transilvaniei",
  zona_aprox=1, judet="—", regiune="Dobrogea / Moldova / Transilvania",
  lat=45.8, lng=26.5,
  participanti="Cimerieni și valuri timpurii de sciți (nomazi nord-pontici) vs. populații autohtone tracice (proto-geto-daci)",
  descriere="Primele valuri de nomazi călăreți din stepele nord-pontice (asociate cu cimerienii și cu pre-sciții) pătrund spre vest, aducând cavaleria ușoară, arcurile cu vârfuri de bronz și pumnalele de tip akinakes. Pătrunderea lor în Dobrogea, Moldova și estul Transilvaniei a generat ciocniri violente cu populația locală. Nu s-au păstrat nume de bătălii sau conducători, dovezile fiind exclusiv arheologice.",
  rezultat="Conflicte locale de apărare; așezări incendiate și fortificații întărite",
  teritoriu="da",
  observatii="Fără izvoare scrise; datare pe bază de arheologie. Zona este aproximativă.",
  sursa="batalii.csv — sec. VIII î.Hr., pct. 1"),
 dict(
  titlu="Conflicte inter-tribale pentru resurse (Cultura Basarabi)",
  tip="Conflict inter-tribal",
  data_start="c. -800", data_end="c. -701", an_start=-800, an_end=-701,
  secol="sec. VIII î.Hr.", secol_n=-8,
  locatie="Oltenia, Banat, Muntenia și Transilvania",
  zona_aprox=1, judet="—", regiune="Oltenia / Banat / Muntenia / Transilvania",
  lat=45.3, lng=23.5,
  participanti="Triburi tracice nordice (cultura Basarabi) — confruntări reciproce",
  descriere="Generalizarea metalurgiei fierului favorizează apariția unei aristocrații militare, iar triburile locale se luptă între ele pentru controlul zăcămintelor de fier, minelor de sare din Transilvania, turmelor și rutelor comerciale. Apar numeroase așezări fortificate cu valuri de pământ, palisade și șanțuri, iar descoperirile de tezaure de arme și straturile de cenușă atestă conflicte repetate.",
  rezultat="Consolidarea elitelor militare și fortificarea așezărilor; fără unificare politică",
  teritoriu="da",
  observatii="Eveniment tip, fără nume proprii; distribuția spațială aproximativă.",
  sursa="batalii.csv — sec. VIII î.Hr., pct. 2"),
 dict(
  titlu="Presiunea triburilor ilire în sud-vest",
  tip="Conflicte de frontieră",
  data_start="c. -800", data_end="c. -701", an_start=-800, an_end=-701,
  secol="sec. VIII î.Hr.", secol_n=-8,
  locatie="Sud-vestul teritoriului actual: sudul Olteniei și Banatul",
  zona_aprox=1, judet="—", regiune="Oltenia / Banat",
  lat=44.9, lng=22.3,
  participanti="Triburi ilire (Balcanii de Vest) vs. comunități tracice locale",
  descriere="La frontiera din sud-vest (Oltenia, Banat) se înregistrează interacțiuni și conflicte cu triburile ilire din vestul Balcanilor. Presiunea i-a determinat pe localnici să-și fortifice așezările pe forme de relief greu accesibile (promontorii, dealuri).",
  rezultat="Întărirea apărării locale; conflicte de intensitate redusă, de frontieră",
  teritoriu="da",
  observatii="Zonă aproximativă; fără evenimente nominale.",
  sursa="batalii.csv — sec. VIII î.Hr., pct. 3"),
 dict(
  titlu="Expansiunea și invaziile sciților",
  tip="Invazii / incursiuni nomade",
  data_start="c. -700", data_end="c. -601", an_start=-700, an_end=-601,
  secol="sec. VII î.Hr.", secol_n=-7,
  locatie="Dobrogea, Moldova și bazinul Mureșului",
  zona_aprox=1, judet="—", regiune="Dobrogea / Moldova / Transilvania (est)",
  lat=46.0, lng=25.5,
  participanti="Sciți (nomazi indo-iranieni nord-pontici) vs. populații geto-trace locale",
  descriere="Sciții pătrund masiv în spațiul carpato-danubiano-pontic, intrând în coliziune cu populațiile geto-trace din Dobrogea, Moldova și din interiorul arcului carpatic (bazinul Mureșului). Dovezile sunt vârfurile de săgeți scitice cu trei muchii înfipte în palisade, straturile de cenușă ale fortificațiilor incendiate și apariția pumnalelor scurte (akinakes).",
  rezultat="Raiduri și devastări; întărirea apărării locale",
  teritoriu="da",
  observatii="Fără evenimente nominale.",
  sursa="batalii.csv — sec. VII î.Hr., pct. 1"),
 dict(
  titlu="Întemeierea coloniei Histria și conflictele de coastă",
  tip="Conflict colonial / de frontieră",
  data_start="c. -657", data_end="c. -600", an_start=-657, an_end=-600,
  secol="sec. VII î.Hr.", secol_n=-7,
  locatie="Litoralul Mării Negre — Histria (jud. Constanța)",
  zona_aprox=0, judet="Constanța", regiune="Dobrogea",
  lat=44.548, lng=28.775,
  participanti="Coloniști greci din Milet (Histria) vs. comunități locale de geți",
  descriere="La mijlocul secolului VII î.Hr. (în jurul anului 657 î.Hr.), grecii din Milet întemeiază Histria, prima colonie grecească de pe țărmul vestic al Mării Negre. Stabilirea nu a fost complet pașnică: colonizarea a generat conflicte de frontieră cu geții pentru controlul pământurilor agricole și al rutelor comerciale, cu tensiuni și asedii sporadice din partea triburilor din hinterland în primele decenii.",
  rezultat="Consolidarea coloniei după o perioadă de tensiuni; ulterior alianțe comerciale",
  teritoriu="da",
  observatii="Datarea întemeierii (c. 657 î.Hr.) este convențională.",
  sursa="batalii.csv — sec. VII î.Hr., pct. 2"),
 dict(
  titlu="Conflicte inter-tribale geto-trace",
  tip="Conflict inter-tribal",
  data_start="c. -700", data_end="c. -601", an_start=-700, an_end=-601,
  secol="sec. VII î.Hr.", secol_n=-7,
  locatie="Teritoriul geto-dac (fără localizare precisă)",
  zona_aprox=1, judet="—", regiune="Geto-Dacia",
  lat=45.5, lng=25.0,
  participanti="Triburi geto-trace (confruntări reciproce)",
  descriere="Numărul așezărilor fortificate autohtone crește; triburile de geți se află adesea în război unele cu altele pentru controlul zăcămintelor și al centrelor de prelucrare a metalelor (mai ales fierul) și pentru rutele comerciale de-a lungul Dunării și spre Marea Neagră.",
  rezultat="Fără unificare; continuarea fragmentării tribale",
  teritoriu="da",
  observatii="Eveniment tip — nu există nume de confruntări.",
  sursa="batalii.csv — sec. VII î.Hr., pct. 3"),
 dict(
  titlu="Campania lui Darius I împotriva sciților (trecerea Dunării)",
  tip="Campanie / invazie",
  data_start="-513", data_end="-513", an_start=-513, an_end=-513,
  secol="sec. VI î.Hr.", secol_n=-6,
  locatie="Dobrogea; podul de vase peste Dunăre în zona Isaccea (jud. Tulcea)",
  zona_aprox=1, judet="Tulcea / Constanța", regiune="Dobrogea",
  lat=45.27, lng=28.46,
  participanti="Imperiul Persan Ahemenid (Darius I) vs. geții din Dobrogea și sciții",
  descriere="Darius I organizează o expediție uriașă împotriva sciților din nordul Mării Negre, al cărei traseu traversează Dobrogea. Spre deosebire de celelalte triburi trace, care s-au predat, geții din Dobrogea opun o rezistență îndârjită; deși învinși numeric, sunt lăudați de Herodot ca fiind „cei mai viteji și mai drepți dintre traci”. După înfrângerea geților, Darius ordonă construirea unui pod de vase peste Dunăre (în zona actualului oraș Isaccea) pentru a trece în stepele scitice.",
  rezultat="Victorie persană la Dunăre; geții învinși dar lăudați de Herodot",
  teritoriu="da",
  observatii="Datarea 513 î.Hr.; localizarea podului este aproximativă.",
  sursa="batalii.csv — sec. VI î.Hr."),
 dict(
  titlu="Conflictele dintre geți și coloniile grecești pontice",
  tip="Conflicte de frontieră",
  data_start="c. -600", data_end="c. -501", an_start=-600, an_end=-501,
  secol="sec. VI î.Hr.", secol_n=-6,
  locatie="Litoralul Mării Negre: Histria, Tomis (Constanța), Callatis (Mangalia)",
  zona_aprox=1, judet="Constanța", regiune="Dobrogea",
  lat=44.0, lng=28.6,
  participanti="Cetăți grecești (Histria, Tomis, Callatis) vs. aristocrație getică locală",
  descriere="Pe litoral se înființează cetăți grecești (Histria în sec. VII, Tomis și Callatis în sec. VI–V î.Hr.). Relațiile dintre greci și aristocrația getică alternează între schimburi comerciale intense și ciocniri violente pentru controlul teritoriilor agricole (chora).",
  rezultat="Tensiuni recurente, fără eliminarea coloniilor",
  teritoriu="da",
  observatii="Eveniment tip, fără bătălii nominale.",
  sursa="batalii.csv — sec. VI î.Hr."),
 dict(
  titlu="Incursiunile scitice la vest de Prut și în Câmpia Română",
  tip="Incursiuni de jaf",
  data_start="c. -600", data_end="c. -501", an_start=-600, an_end=-501,
  secol="sec. VI î.Hr.", secol_n=-6,
  locatie="Vest de Prut (Moldova) și Câmpia Română",
  zona_aprox=1, judet="—", regiune="Moldova / Muntenia",
  lat=46.2, lng=27.0,
  participanti="Sciți nomazi vs. triburi sedentare geto-dace",
  descriere="Triburile scitice pătrund la vest de Prut și în Câmpia Română pentru pradă sau extinderea zonelor de pășunat, intrând în conflict direct cu triburile sedentare geto-dace.",
  rezultat="Conflicte de pradă și apărare; fără schimbări teritoriale majore",
  teritoriu="da",
  observatii="Zonă aproximativă.",
  sursa="batalii.csv — sec. VI î.Hr."),
 dict(
  titlu="Războaie inter-tribale în Epoca Fierului (Hallstatt târziu)",
  tip="Conflict inter-tribal",
  data_start="c. -600", data_end="c. -501", an_start=-600, an_end=-501,
  secol="sec. VI î.Hr.", secol_n=-6,
  locatie="Spațiul geto-dac (Hallstatt târziu)",
  zona_aprox=1, judet="—", regiune="Geto-Dacia",
  lat=45.5, lng=25.0,
  participanti="Uniuni de triburi geto-dace (confruntări reciproce)",
  descriere="Comunitățile autohtone sunt fragmentate în uniuni de triburi care se atacă reciproc pentru resurse, pământ și prestigiu militar, confirmate arheologic prin tezaure de arme și așezări incendiate.",
  rezultat="Slăbiciune politică cronică înainte de unificarea dacică",
  teritoriu="da",
  observatii="Eveniment tip, fără nume proprii.",
  sursa="batalii.csv — sec. VI î.Hr."),
 dict(
  titlu="Prăbușirea stăpânirii persane la nord de Balcani și conflictele de eliberare",
  tip="Răscoală / conflicte locale",
  data_start="c. -500", data_end="c. -480", an_start=-500, an_end=-480,
  secol="sec. V î.Hr.", secol_n=-5,
  locatie="Dobrogea și spațiul tracic de la nord de Balcani",
  zona_aprox=1, judet="—", regiune="Dobrogea",
  lat=44.4, lng=28.2,
  participanti="Geți și sciți vs. garnizoane persane rămase în Tracia",
  descriere="După campania din 513 î.Hr., regiunea rămâne sub o relativă influență sau supraveghere persană. Odată cu înfrângerile perșilor în Grecia (Războaiele Persane), stăpânirea lor la nord de Balcani se prăbușește, declanșând conflicte locale de eliberare și reașezări de forțe între geți, sciți și garnizoanele persane.",
  rezultat="Retragerea influenței persane; reconfigurare locală de putere",
  teritoriu="da",
  observatii="Fără bătălii nominale; datare aproximativă.",
  sursa="batalii.csv — sec. V î.Hr., pct. 1"),
 dict(
  titlu="Conflictele de frontieră dintre geți și Regatul Odris",
  tip="Războaie de expansiune",
  data_start="c. -480", data_end="c. -430", an_start=-480, an_end=-430,
  secol="sec. V î.Hr.", secol_n=-5,
  locatie="Dobrogea (dreapta Dunării) și stânga Dunării",
  zona_aprox=1, judet="—", regiune="Dobrogea",
  lat=44.3, lng=28.0,
  participanti="Regatul Odris (Teres I) vs. triburi getice din Dobrogea",
  descriere="Regele odris Teres I unifică triburile trace din sud și extinde regatul spre nord, până la Dunăre, ceea ce duce la ciocniri militare inevitabile cu geții din Dobrogea. Conflictele se stabilizează printr-o formă de suzeranitate: geții sunt integrați parțial în sfera odrisă, plătesc tribut și devin aliați militari (arcași călare).",
  rezultat="Suzeranitate odrisă asupra geților dobrogeni",
  teritoriu="da",
  observatii="Zonă aproximativă.",
  sursa="batalii.csv — sec. V î.Hr., pct. 2"),
 dict(
  titlu="Conflictul odriso-scitic de la Dunăre (Scyles vs. Sitalces)",
  tip="Conflict de frontieră",
  data_start="c. -450", data_end="c. -450", an_start=-450, an_end=-450,
  secol="sec. V î.Hr.", secol_n=-5,
  locatie="Dunărea de Jos (limesul fluvial)",
  zona_aprox=1, judet="—", regiune="Dobrogea",
  lat=45.2, lng=28.5,
  participanti="Sciți (regele Scyles) vs. Regatul Odris (regele Sitalces)",
  descriere="Expansiunea sciților conduși de Scyles spre Dunăre provoacă un conflict militar direct cu Regatul Odris al lui Sitalces. Războiul deschis este evitat prin intermediul unei alianțe matrimoniale și stabilirea graniței pe Dunăre, dar tensiunile armate de frontieră rămân constante.",
  rezultat="Evitarea războiului deschis; graniță pe Dunăre; tensiuni persistente",
  teritoriu="da",
  observatii="Datare aproximativă (c. 450 î.Hr.).",
  sursa="batalii.csv — sec. V î.Hr., pct. 3"),
 dict(
  titlu="Invaziile scitice în Moldova și estul Transilvaniei",
  tip="Incursiuni de jaf",
  data_start="c. -500", data_end="c. -401", an_start=-500, an_end=-401,
  secol="sec. V î.Hr.", secol_n=-5,
  locatie="Moldova și estul Transilvaniei",
  zona_aprox=1, judet="—", regiune="Moldova / Transilvania (est)",
  lat=46.5, lng=26.5,
  participanti="Sciți nomazi vs. geți sedentari",
  descriere="Arheologia confirmă conflicte locale violente: vârfuri de săgeți scitice cu trei muchii, specifice sec. V î.Hr., descoperite în așezări autohtone din Moldova și estul Transilvaniei, demonstrează incursiuni militare de jaf și confruntări sângeroase între geți și sciți.",
  rezultat="Raiduri și devastări; apărare locală fragmentată",
  teritoriu="da",
  observatii="Eveniment tip, în baza dovezilor arheologice.",
  sursa="batalii.csv — sec. V î.Hr., pct. 3"),
 dict(
  titlu="Conflictele legate de coloniile grecești: distrugerea și refacerea Histriei",
  tip="Conflict local / asediu",
  data_start="c. -500", data_end="c. -480", an_start=-500, an_end=-480,
  secol="sec. V î.Hr.", secol_n=-5,
  locatie="Histria (jud. Constanța)",
  zona_aprox=0, judet="Constanța", regiune="Dobrogea",
  lat=44.548, lng=28.775,
  participanti="Histria (cetate greacă) vs. triburi de geți și sciți din hinterland",
  descriere="Orașele-stat grecești (Histria, Tomis, Callatis) își apără teritoriul agricol prin războaie locale împotriva triburilor din hinterland, care organizau atacuri pentru pradă sau cereau tribut. Histria este parțial distrusă spre sfârșitul sec. VI sau începutul sec. V î.Hr., cel mai probabil în urma unui astfel de conflict, fiind ulterior reconstruită și fortificată masiv.",
  rezultat="Distrugere parțială urmată de reconstrucție și fortificare",
  teritoriu="da",
  observatii="Datarea distrugerii este estimată pe baza arheologiei.",
  sursa="batalii.csv — sec. V î.Hr., pct. 4"),
 dict(
  titlu="Expediția lui Alexandru cel Mare la nord de Dunăre",
  tip="Campanie / expediție",
  data_start="-335", data_end="-335", an_start=-335, an_end=-335,
  secol="sec. IV î.Hr.", secol_n=-4,
  locatie="Zona Zimnicea — malul nordic al Dunării (jud. Teleorman)",
  zona_aprox=1, judet="Teleorman", regiune="Muntenia (sud)",
  lat=43.655, lng=25.367,
  participanti="Regatul Macedoniei (Alexandru cel Mare) vs. geți",
  descriere="În primăvara anului 335 î.Hr., Alexandru cel Mare pornește o campanie în Balcani pentru a pacifica triburile răzvrătite; urmărindu-i pe tribali până la Dunăre (probabil în zona Zimnicea), este întâmpinat pe malul nordic de o oaste getică de circa 14.000 de luptători. Alexandru trece fluviul noaptea cu bărci improvizate (monoxile) și burdufuri, surprinde oastea getică, care se retrage, și îi distruge o așezare fortificată.",
  rezultat="Victorie macedoneană și pradă; consolidarea autorității lui Alexandru",
  teritoriu="da",
  observatii="Localizarea exactă a trecerii este probabilă (zona Zimnicea).",
  sursa="batalii.csv — sec. IV î.Hr., pct. 1"),
 dict(
  titlu="Dezastrul expediției lui Zopyrion",
  tip="Campanie / înfrângere",
  data_start="c. -331", data_end="c. -325", an_start=-331, an_end=-325,
  secol="sec. IV î.Hr.", secol_n=-4,
  locatie="Gurile Dunării și Dobrogea (retragerea)", zona_aprox=1, judet="Tulcea / Constanța",
  regiune="Dobrogea", lat=45.1, lng=28.8,
  participanti="Regatul Macedoniei (Zopyrion, ~30.000 de soldați) vs. coaliție de geți și sciți",
  descriere="În timp ce Alexandru era în Asia, guvernatorul Traciei, Zopyrion, organizează o expediție spre nordul Mării Negre; după asediul eșuat al cetății Olbia, armata se retrage haotic prin teritoriile de la gurile Dunării și Dobrogea, unde este blocată de o furtună. Profitând de vulnerabilitate, geții și sciții atacă și nimicesc complet armata macedoneană, iar Zopyrion este ucis.",
  rezultat="Anihilarea armatei macedonene; victorie a coaliției locale",
  teritoriu="da",
  observatii="Datare aproximativă (c. 331–325 î.Hr.); locul uciderii nu este precis.",
  sursa="batalii.csv — sec. IV î.Hr., pct. 2"),
 dict(
  titlu="Începutul războaielor dintre Lysimah și Dromichaetes",
  tip="Război / campanie",
  data_start="c. -320", data_end="c. -292", an_start=-320, an_end=-292,
  secol="sec. IV–III î.Hr.", secol_n=-4,
  locatie="Câmpia Română (teritoriile getice)",
  zona_aprox=1, judet="—", regiune="Muntenia / Oltenia",
  lat=44.6, lng=25.5,
  participanti="Regatul Macedoniei/Tracia (Lysimah) vs. Regatul getic (Dromichaetes)",
  descriere="După moartea lui Alexandru cel Mare, generalul Lysimah preia Tracia și încearcă să-și extindă stăpânirea la nord de Dunăre. Geții lui Dromichaetes aplică tactica pământului pârjolit și hărțuirea continuă; slăbite de foame și sete, armatele macedonene suferă înfrângeri repetate. Conflictul culminează în jurul anului 292 î.Hr. cu capturarea lui Lysimah și o pace celebră.",
  rezultat="Victoria diplomatică și militară a geților; păcii i-au succedat retrocedarea cetăților dunărene",
  teritoriu="da",
  observatii="Evenimentul este reluat și mai detaliat la sec. III î.Hr.",
  sursa="batalii.csv — sec. IV î.Hr., pct. 3"),
 dict(
  titlu="Pătrunderea triburilor celtice în Transilvania",
  tip="Invazie / migrație armată",
  data_start="c. -320", data_end="c. -280", an_start=-320, an_end=-280,
  secol="sec. IV–III î.Hr.", secol_n=-4,
  locatie="Transilvania și Oltenia",
  zona_aprox=1, judet="—", regiune="Transilvania / Oltenia",
  lat=46.2, lng=24.0,
  participanti="Triburi celtice (printre care scordiscii) vs. comunități geto-dace",
  descriere="Triburile celtice migrează masiv spre interiorul Arcului Carpatic și Balcani; intrarea lor în Transilvania și Oltenia nu a fost pașnică, arheologia indicând conflicte violente cu comunitățile autohtone pentru controlul resurselor de sare și metale. După faza inițială de confruntări, cele două populații ajung la coabitare, celții fiind asimilați treptat.",
  rezultat="Conflicte inițiale urmate de coabitare și asimilare",
  teritoriu="da",
  observatii="Zonă aproximativă, fără bătălii nominale.",
  sursa="batalii.csv — sec. IV î.Hr., pct. 4"),
]
