# -*- coding: utf-8 -*-
"""Partea 3 - Sec. I - IV d.Hr. (Dacia romană)"""
EVENTS = [
 dict(
  titlu="Campania lui Sextus Aelius Catus la nord de Dunăre",
  tip="Expediție punitivă / deportare",
  data_start="c. 11", data_end="c. 12", an_start=11, an_end=12,
  secol="sec. I d.Hr.", secol_n=1,
  locatie="Nord de Dunăre (sudul Munteniei / Dobrogea) — fără localizare precisă",
  zona_aprox=1, judet="—", regiune="Muntenia / Dobrogea",
  lat=44.3, lng=26.5,
  participanti="Imperiul Roman (Sextus Aelius Catus) vs. geți (uniuni de triburi)",
  descriere="După destrămarea regatului lui Burebista, dacii erau divizați și atacau frecvent provincia Moesia. Generalul roman Sextus Aelius Catus conduce o expediție de pedepsire la nord de Dunăre și strămută forțat circa 50.000 de geți în sudul fluviului, pentru a-i aduce sub control roman și a depopula zona folosită ca bază de atac.",
  rezultat="Depopulare parțială a zonei de nord a Dunării și întărirea frontierei romane",
  teritoriu="da",
  observatii="Datare aproximativă (c. 11–12 d.Hr.).",
  sursa="batalii.csv — sec. I d.Hr., pct. 1"),
 dict(
  titlu="Campania lui Plautius Silvanus Aelianus peste Dunăre",
  tip="Expediție / pacificare",
  data_start="c. 57", data_end="c. 67", an_start=57, an_end=67,
  secol="sec. I d.Hr.", secol_n=1,
  locatie="Nord de Dunăre (Muntenia, zona gurilor Dunării)",
  zona_aprox=1, judet="—", regiune="Muntenia / Dobrogea",
  lat=44.5, lng=27.5,
  participanti="Imperiul Roman (Plautius Silvanus Aelianus) vs. sarmați, bastarni și daci",
  descriere="În timpul lui Nero, guvernatorul Moesiei, Plautius Silvanus Aelianus, intervine militar la nord de Dunăre din cauza mișcărilor de populații barbare. Pacifică regiunea și strămută peste 100.000 de transdanubieni (daci, bastarni, sarmați) la sud de fluviu, obligându-i să plătească tribut Romei.",
  rezultat="Pacifiere temporară a frontierei dunărene; tribut roman",
  teritoriu="da",
  observatii="Datare aproximativă; zona fără localizare precisă.",
  sursa="batalii.csv — sec. I d.Hr., pct. 2"),
 dict(
  titlu="Războiul daco-roman al lui Domițian — atacul dacic din 85–86",
  tip="Război / invazie",
  data_start="85", data_end="86", an_start=85, an_end=86,
  secol="sec. I d.Hr.", secol_n=1,
  locatie="Dunărea de Jos, Moesia (Dobrogea de astăzi)",
  zona_aprox=1, judet="Constanța / Tulcea", regiune="Dobrogea",
  lat=44.3, lng=28.0,
  participanti="Regatul Dac (Duras, apoi Decebal) vs. Imperiul Roman (Moesia)",
  descriere="Dacii trec iarna Dunărea înghețată, devastează Moesia și îl ucid pe guvernatorul Oppius Sabinus. Este cel mai mare conflict al secolului I pe teritoriul României, declanșat de regele dac Duras și continuat sub Decebal.",
  rezultat="Devastarea Moesiei; represalii romane ulterioare",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. I d.Hr., pct. 3"),
 dict(
  titlu="Prima bătălie de la Tapae (Cornelius Fuscus)",
  tip="Bătălie",
  data_start="87", data_end="87", an_start=87, an_end=87,
  secol="sec. I d.Hr.", secol_n=1,
  locatie="Trecătoarea Tapae — Porțile de Fier ale Transilvaniei (Caraș-Severin / Hunedoara)",
  zona_aprox=1, judet="Caraș-Severin / Hunedoara", regiune="Transilvania (sud-vest)",
  lat=45.4, lng=22.5,
  participanti="Imperiul Roman (Cornelius Fuscus, Legiunea a V-a Alaudae) vs. Regatul Dac (Decebal)",
  descriere="Împăratul Domițian trimite la nord de Dunăre o armată uriașă sub comanda prefectului pretoriului Cornelius Fuscus. Armata romană cade într-o ambuscadă în trecătoarea Tapae: dacii obțin o victorie zdrobitoare, Fuscus este ucis, Legiunea a V-a Alaudae este masacrată, iar romanii pierd steagurile și mașinile de război.",
  rezultat="Victorie dacică decisivă; dezastru militar roman",
  teritoriu="da",
  observatii="Identificarea locației Tapae este disputată (Porțile de Fier ale Transilvaniei).",
  sursa="batalii.csv — sec. I d.Hr., pct. 3"),
 dict(
  titlu="A doua bătălie de la Tapae (Tettius Iulianus)",
  tip="Bătălie",
  data_start="88", data_end="88", an_start=88, an_end=88,
  secol="sec. I d.Hr.", secol_n=1,
  locatie="Trecătoarea Tapae — Porțile de Fier ale Transilvaniei (Caraș-Severin / Hunedoara)",
  zona_aprox=1, judet="Caraș-Severin / Hunedoara", regiune="Transilvania (sud-vest)",
  lat=45.4, lng=22.5,
  participanti="Imperiul Roman (Tettius Iulianus) vs. Regatul Dac (Decebal)",
  descriere="Domițian trimite o nouă armată sub comanda generalului Tettius Iulianus. Romanii câștigă bătălia de la Tapae și provoacă pierderi mari dacilor, dar nu pot înainta spre capitala Sarmizegetusa Regia din cauza terenului dificil și a altor revolte barbare la granițele imperiului.",
  rezultat="Victorie romană tactică, fără finalizarea cuceririi Daciei",
  teritoriu="da",
  observatii="Identificarea locației Tapae este disputată.",
  sursa="batalii.csv — sec. I d.Hr., pct. 3"),
 dict(
  titlu="Pacea din 89 d.Hr. între Domițian și Decebal",
  tip="Încheiere de pace (final al războiului)",
  data_start="89", data_end="89", an_start=89, an_end=89,
  secol="sec. I d.Hr.", secol_n=1,
  locatie="Dunărea de Jos (frontiera daco-romană)",
  zona_aprox=1, judet="—", regiune="Dobrogea / Muntenia (sud)",
  lat=44.4, lng=26.8,
  participanti="Imperiul Roman (Domițian) vs. Regatul Dac (Decebal)",
  descriere="Pace de compromis: Decebal devine client al Romei, primind subsidii în bani, meșteri militari și ingineri, resurse pe care le folosește pentru a-și fortifica regatul înaintea războaielor cu Traian. Evenimentul închide ciclul războiului din 85–89.",
  rezultat="Pace de compromis; Dacia clientă a Romei, dar rearmată",
  teritoriu="da",
  observatii="Inclus pentru continuitatea cronologică a războaielor daco-romane.",
  sursa="batalii.csv — sec. I d.Hr., pct. 3"),
 dict(
  titlu="Primul Război Daco-Roman (101–102)",
  tip="Război / campanie",
  data_start="101", data_end="102", an_start=101, an_end=102,
  secol="sec. II d.Hr.", secol_n=2,
  locatie="Dacia (Banat, Transilvania de sud) și Dobrogea",
  zona_aprox=1, judet="—", regiune="Dacia / Dobrogea",
  lat=45.5, lng=23.0,
  participanti="Imperiul Roman (împăratul Traian) vs. Regatul Dac (Decebal)",
  descriere="Primul dintre cele două războaie majore daco-romane: Traian traversează Dunărea pentru a neutraliza puterea militară a dacilor. Include bătăliile de la Tapae și Adamclisi; se încheie cu o pace provizorie (102 d.Hr.), prin care Decebal acceptă condițiile romane, dar le încalcă ulterior.",
  rezultat="Pace provizorie în 102; Dacia devine regat client cu condiții umilitoare",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. II d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Tapae (101)",
  tip="Bătălie",
  data_start="101", data_end="101", an_start=101, an_end=101,
  secol="sec. II d.Hr.", secol_n=2,
  locatie="Trecătoarea Tapae — Porțile de Fier ale Transilvaniei (Caraș-Severin / Hunedoara)",
  zona_aprox=1, judet="Caraș-Severin / Hunedoara", regiune="Transilvania (sud-vest)",
  lat=45.4, lng=22.5,
  participanti="Imperiul Roman (Traian) vs. Regatul Dac (Decebal)",
  descriere="În campania din 101, trupele romane obțin o victorie grea în fața dacilor la „Porțile de Fier ale Transilvaniei”, deschizând drumul spre interiorul Daciei, dar nu și cucerirea imediată a capitalei.",
  rezultat="Victorie romană dificilă",
  teritoriu="da",
  observatii="Identificarea locației este disputată.",
  sursa="batalii.csv — sec. II d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Adamclisi (iarna 101–102)",
  tip="Bătălie",
  data_start="101", data_end="102", an_start=101, an_end=102,
  secol="sec. II d.Hr.", secol_n=2,
  locatie="Adamclisi (județul Constanța)",
  zona_aprox=0, judet="Constanța", regiune="Dobrogea",
  lat=44.083, lng=27.953,
  participanti="Imperiul Roman (Traian) vs. daci și sarmați roxolani",
  descriere="O contraofensivă de amploare a dacilor, aliați cu sarmații roxolani la sudul Dunării, este zdrobită de Traian. Victoria romană este comemorată prin monumentul triumfal de la Adamclisi (Tropaeum Traiani).",
  rezultat="Victoria romană; consolidarea controlului asupra Dobrogei",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. II d.Hr., pct. 1"),
 dict(
  titlu="Al Doilea Război Daco-Roman și căderea Sarmizegetusei (105–106)",
  tip="Război / cucerire",
  data_start="105", data_end="106", an_start=105, an_end=106,
  secol="sec. II d.Hr.", secol_n=2,
  locatie="Dacia (capitala Sarmizegetusa Regia, jud. Hunedoara)",
  zona_aprox=0, judet="Hunedoara", regiune="Transilvania",
  lat=45.623, lng=23.310,
  participanti="Imperiul Roman (Traian) vs. Regatul Dac (Decebal)",
  descriere="Declanșat după încălcarea condițiilor păcii din 102 de către Decebal. Romanii atacă pe mai multe fronturi, asediază și distrug capitala Sarmizegetusa Regia; Decebal se sinucide pentru a nu cădea prizonier, iar o mare parte a Daciei devine provincie romană.",
  rezultat="Cucerirea Daciei și crearea provinciei romane Dacia",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. II d.Hr., pct. 1"),
 dict(
  titlu="Asediul și distrugerea Sarmizegetusei Regia",
  tip="Asediu",
  data_start="106", data_end="106", an_start=106, an_end=106,
  secol="sec. II d.Hr.", secol_n=2,
  locatie="Sarmizegetusa Regia — Grădiștea de Munte (județul Hunedoara)",
  zona_aprox=0, judet="Hunedoara", regiune="Transilvania",
  lat=45.623, lng=23.310,
  participanti="Imperiul Roman (Traian) vs. Regatul Dac (Decebal)",
  descriere="Efectivul final al celui de-al doilea război: capitalele regatului dacic sunt asediate și distruse de legiunile romane. Decebal se sinucide, iar tezaurul regal este capturat; evenimentul marchează sfârșitul regatului dac independent.",
  rezultat="Căderea capitalei dacice; sfârșitul regatului lui Decebal",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. II d.Hr., pct. 1"),
 dict(
  titlu="Atacurile dacilor liberi și ale iazigilor asupra Daciei romane",
  tip="Invazii / conflicte de frontieră",
  data_start="117", data_end="118", an_start=117, an_end=118,
  secol="sec. II d.Hr.", secol_n=2,
  locatie="Provincia Dacia (Transilvania, Banat, Câmpia de Vest)",
  zona_aprox=1, judet="—", regiune="Dacia",
  lat=46.3, lng=23.0,
  participanti="Dacii liberi și sarmații (iazigi din Câmpia de Vest, roxolani din Moldova/Muntenia) vs. Imperiul Roman",
  descriere="Moartea împăratului Traian (117 d.Hr.) declanșează o criză majoră la frontierele noii provincii Dacia: dacii rămași în afara granițelor, în alianță cu triburile sarmate, atacă violent provincia. Guvernatorul Gaius Julius Quadratus Bassus este ucis în lupte, iar Hadrian vine personal pe Dunăre și reorganizează administrativ și militar regiunea.",
  rezultat="Respigerea atacurilor; reorganizarea apărării provinciei",
  teritoriu="da",
  observatii="Zonă aproximativă.",
  sursa="batalii.csv — sec. II d.Hr., pct. 2"),
 dict(
  titlu="Războaiele Marcomanice — atacurile asupra Daciei",
  tip="Războaie / invazii",
  data_start="166", data_end="180", an_start=166, an_end=180,
  secol="sec. II d.Hr.", secol_n=2,
  locatie="Dacia (Transilvania și Banat)",
  zona_aprox=1, judet="—", regiune="Dacia",
  lat=46.2, lng=23.2,
  participanti="Coaliție de triburi germanice și sarmate (marcomani, cvazi, iazigi, bastarni, daci liberi) vs. Imperiul Roman (Marcus Aurelius)",
  descriere="În timpul domniei lui Marcus Aurelius, o coaliție uriașă de triburi germanice și sarmate atacă frontierele imperiului, inclusiv Dacia. Transilvania și Banatul sunt puternic afectate de incursiunile iazigilor și ale dacilor liberi. Romanii reușesc cu greu să stabilizeze situația, transformând Dacia într-o zonă puternic militarizată (Legiunea a V-a Macedonica este adusă la Potaissa — Turda).",
  rezultat="Stabilizare dificilă; militarizare intensă a Daciei",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. II d.Hr., pct. 3"),
 dict(
  titlu="Invazia costobocilor (170 d.Hr.)",
  tip="Invazie",
  data_start="170", data_end="170", an_start=170, an_end=170,
  secol="sec. II d.Hr.", secol_n=2,
  locatie="Dacia și, în înaintare, spre Balcani și Grecia",
  zona_aprox=1, judet="—", regiune="Dacia / Balcani",
  lat=46.0, lng=24.0,
  participanti="Costoboci (daci liberi din nordul și nord-estul României) vs. Imperiul Roman",
  descriere="În cadrul războaielor marcomanice, dacii liberi costoboci străpung liniile romane, devastează Dacia și coboară prin Balcani până în Grecia, înainte de a fi opriți și respinși.",
  rezultat="Devastarea Daciei; respingerea ulterioară a invadatorilor",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. II d.Hr., pct. 3"),
 dict(
  titlu="Atacurile carpilor și ale dacilor liberi (214–248)",
  tip="Invazii / conflicte recurente",
  data_start="214", data_end="248", an_start=214, an_end=248,
  secol="sec. III d.Hr.", secol_n=3,
  locatie="Provincia Dacia și Moesia (Dobrogea de astăzi)",
  zona_aprox=1, judet="—", regiune="Dacia / Dobrogea",
  lat=45.8, lng=26.0,
  participanti="Carpii și dacii liberi (costoboci) vs. Imperiul Roman",
  descriere="Profitând de slăbirea Romei, carpii (zona Moldovei) și costobocii atacă în mod repetat garnizoanele romane din Dacia și Moesia. Campaniile romane se întind pe mai multe decenii, iar frontiera este supusă unei presiuni constante.",
  rezultat="Slăbirea treptată a apărării romane; pierderi teritoriale ulterioare",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. III d.Hr., pct. 1"),
 dict(
  titlu="Războiul lui Maximin Tracul împotriva carpilor și iazigilor",
  tip="Război / campanie",
  data_start="236", data_end="238", an_start=236, an_end=238,
  secol="sec. III d.Hr.", secol_n=3,
  locatie="Linia Dunării și Dacia",
  zona_aprox=1, judet="—", regiune="Dacia / Dobrogea",
  lat=44.8, lng=24.5,
  participanti="Imperiul Roman (Maximin Tracul) vs. carpi și sarmați iazigi",
  descriere="Împăratul roman Maximin Tracul vine personal pe linia Dunării și în Dacia pentru a respinge atacurile violente ale carpilor și ale sarmaților iazigi, obținând succese temporare în fața acestora.",
  rezultat="Represalii romane reușite; consolidare temporară a frontierei",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. III d.Hr., pct. 1"),
 dict(
  titlu="Invazia carpilor (245–247) și abandonarea Limesului Transalutanus",
  tip="Invazie / ofensivă",
  data_start="245", data_end="247", an_start=245, an_end=247,
  secol="sec. III d.Hr.", secol_n=3,
  locatie="Limes Transalutanus (Muntenia), Câmpia Română",
  zona_aprox=1, judet="—", regiune="Muntenia",
  lat=44.8, lng=25.0,
  participanti="Carpii vs. Imperiul Roman (Filip Arabul)",
  descriere="Carpii declanșează o ofensivă masivă, distrugând fortificațiile romane de pe Limesul Transalutanus (linia defensivă din Muntenia). Împăratul Filip Arabul vine în Dacia și poartă lupte grele; deși îi învinge și primește titlul de Carpicus Maximus, romanii evacuează definitiv această linie, retrăgându-se la vest de râul Olt.",
  rezultat="Victorie romană costisitoare; abandonarea strategică a liniei Transalutanus",
  teritoriu="da",
  observatii="Locația pe hartă este aproximativă (linia Transalutanus).",
  sursa="batalii.csv — sec. III d.Hr., pct. 1"),
 dict(
  titlu="Primul asediu al Sarmizegetusei (Ulpia Traiana) — invazia goților și a coalițiilor barbare",
  tip="Invazie / asediu",
  data_start="c. 248", data_end="c. 249", an_start=248, an_end=249,
  secol="sec. III d.Hr.", secol_n=3,
  locatie="Ulpia Traiana Sarmizegetusa (județul Hunedoara)",
  zona_aprox=0, judet="Hunedoara", regiune="Transilvania",
  lat=45.517, lng=22.787,
  participanti="Coaliție barbară: goți, carpi, taifali, bastarni vs. Imperiul Roman (Dacia)",
  descriere="O armată confederată formată din goți, carpi, taifali și bastarni trece Prutul și Nistrul; un corp de oaste pătrunde adânc în Transilvania, asediind și provocând mari distrugeri capitalei provinciei, Ulpia Traiana Sarmizegetusa.",
  rezultat="Distrugerea parțială a capitalei provinciale; slăbirea Daciei romane",
  teritoriu="da",
  observatii="Datare aproximativă (cca. 248–249).",
  sursa="batalii.csv — sec. III d.Hr., pct. 2"),
 dict(
  titlu="Războaiele „scitice” din Dobrogea (Scythia Minor)",
  tip="Invazii / asedii",
  data_start="248", data_end="270", an_start=248, an_end=270,
  secol="sec. III d.Hr.", secol_n=3,
  locatie="Dobrogea: Histria, Tomis (Constanța), Callatis (Mangalia)",
  zona_aprox=1, judet="Constanța / Tulcea", regiune="Dobrogea",
  lat=44.0, lng=28.4,
  participanti="Goți și heruli vs. Imperiul Roman (Scythia Minor)",
  descriere="Dobrogea este devastată prin atacuri maritime și terestre organizate de goți și heruli. Orașe înfloritoare precum Histria, Tomis și Callatis sunt asediate sau distruse parțial în repetate rânduri, fiind apoi refăcute parțial de către romani.",
  rezultat="Distrugeri masive ale orașelor dobrogene; declin urban",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. III d.Hr., pct. 2"),
 dict(
  titlu="Bătălia de la Naissus (context — în afara teritoriului României)",
  tip="Bătălie (context regional)",
  data_start="269", data_end="269", an_start=269, an_end=269,
  secol="sec. III d.Hr.", secol_n=3,
  locatie="Naissus (azi Niș, Serbia) — în afara teritoriului actual al României",
  zona_aprox=1, judet="—", regiune="—",
  lat=43.32, lng=21.90,
  participanti="Imperiul Roman (Claudius al II-lea) vs. coaliție de peste 300.000 de goți și heruli",
  descriere="Marea victorie a împăratului Claudius al II-lea (Gothicus) împotriva unei coaliții uriașe de goți și heruli; deși bătălia s-a dat la sud de Dunăre, ea a salvat temporar provinciile romane de pe teritoriul României de la o distrugere completă.",
  rezultat="Victoria romană; reducerea amenințării gotice asupra provinciilor dunărene",
  teritoriu="nu",
  observatii="Inclus ca eveniment de context regional; nu s-a desfășurat pe teritoriul actual al României.",
  sursa="batalii.csv — sec. III d.Hr., pct. 2"),
 dict(
  titlu="Retragerea aureliană din Dacia",
  tip="Retragere strategică / abandonare",
  data_start="271", data_end="275", an_start=271, an_end=275,
  secol="sec. III d.Hr.", secol_n=3,
  locatie="Dacia (întreg teritoriul de la nord de Dunăre)",
  zona_aprox=1, judet="—", regiune="Dacia",
  lat=45.8, lng=23.5,
  participanti="Imperiul Roman (Aurelian) vs. carpi, goți și alte triburi barbare",
  descriere="După ultimele victorii obținute în 271 împotriva carpilor și goților la nord de Dunăre, împăratul Aurelian decide strategic să abandoneze provincia, prea expusă și măcinată de decenii de războaie. Armata și administrația romană părăsesc definitiv teritoriul de la nord de Dunăre, granița imperială mutându-se pe fluviu; fosta provincie este ocupată treptat de vizigoți, carpi și taifali.",
  rezultat="Abandonarea Daciei romane; ocuparea de către triburi germanice",
  teritoriu="da",
  observatii="Eveniment de tip proces strategic, nu bătălie unică.",
  sursa="batalii.csv — sec. III d.Hr., pct. 3"),
 dict(
  titlu="Campaniile lui Constantin cel Mare împotriva goților și carpilor",
  tip="Campanii / expediții",
  data_start="315", data_end="323", an_start=315, an_end=323,
  secol="sec. IV d.Hr.", secol_n=4,
  locatie="Oltenia și Muntenia (la nord de Dunăre)",
  zona_aprox=1, judet="—", regiune="Oltenia / Muntenia",
  lat=44.6, lng=24.3,
  participanti="Imperiul Roman (Constantin cel Mare) vs. goți și carpi",
  descriere="După retragerea aureliană, romanii păstrează capete de pod la nord de Dunăre. Constantin cel Mare declanșează o serie de ofensive majore pentru a-și securiza frontiera și a pedepsi triburile migratoare: armata romană trece Dunărea și poartă lupte grele în Oltenia și Muntenia, respingând atacurile goților și carpilor.",
  rezultat="Respigerea atacurilor; refacerea prestigiului roman la nord de Dunăre",
  teritoriu="da",
  observatii="Zonă aproximativă; fără bătălii nominale în sursă.",
  sursa="batalii.csv — sec. IV d.Hr., pct. 1"),
 dict(
  titlu="Războiul sarmatic-gotic din 332",
  tip="Război / bătălie",
  data_start="332", data_end="332", an_start=332, an_end=332,
  secol="sec. IV d.Hr.", secol_n=4,
  locatie="Bazinele râurilor Mureș și Olt",
  zona_aprox=1, judet="—", regiune="Transilvania / Oltenia",
  lat=45.9, lng=23.0,
  participanti="Imperiul Roman (Constantin cel Mare) vs. goți (tervingi)",
  descriere="Constantin cel Mare obține o victorie zdrobitoare împotriva goților (tervingi) în bazinele râurilor Mureș și Olt. În urma conflictului, goții semnează un tratat de pace (foedus), devenind aliați (foederati) ai Romei și asigurând o perioadă de liniște la frontieră.",
  rezultat="Victorie romană decisivă; foedus cu goții",
  teritoriu="da",
  observatii="Locația exactă a bătăliei nu este cunoscută.",
  sursa="batalii.csv — sec. IV d.Hr., pct. 1"),
 dict(
  titlu="Campania lui Valens din 367 împotriva goților",
  tip="Campanie / expediție punitivă",
  data_start="367", data_end="367", an_start=367, an_end=367,
  secol="sec. IV d.Hr.", secol_n=4,
  locatie="Trecerea Dunării pe la Daphne (lângă Oltenița) și teritoriile tervingilor",
  zona_aprox=1, judet="Călărași", regiune="Muntenia (sud)",
  lat=44.087, lng=26.636,
  participanti="Imperiul Roman de Răsărit (Valens) vs. goți tervingi (Athanaric)",
  descriere="După încălcarea păcii de către goți (care sprijiniseră un pretendent la tronul imperial), Valens organizează expediții punitive masive. În 367, armata romană trece Dunărea pe un pod de vase pe la Daphne (lângă Oltenița) și devastează teritoriile tervingilor, dar aceștia se retrag în Munții Carpați (probabil în Buzău/Vrancea) pentru a evita o bătălie decisivă.",
  rezultat="Devastarea teritoriilor gotice, fără bătălie decisivă",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. IV d.Hr., pct. 2"),
 dict(
  titlu="Campania lui Valens din 369 și pacea de pe Dunăre",
  tip="Campanie / tratat de pace",
  data_start="369", data_end="369", an_start=369, an_end=369,
  secol="sec. IV d.Hr.", secol_n=4,
  locatie="Trecerea pe la Noviodunum (Isaccea, jud. Tulcea) și Dunărea de Jos",
  zona_aprox=1, judet="Tulcea", regiune="Dobrogea",
  lat=45.268, lng=28.458,
  participanti="Imperiul Roman de Răsărit (Valens) vs. goți tervingi (Athanaric)",
  descriere="Romanii atacă din nou, traversând pe la Noviodunum, și obțin o serie de victorii locale împotriva războinicilor conduși de Athanaric. Conflictul se încheie în toamna anului 369 prin faimosul tratat de pace semnat de Valens și Athanaric direct pe o corabie, la mijlocul Dunării.",
  rezultat="Pace semnată pe Dunăre; încetarea ostilităților, graniță pe fluviu",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. IV d.Hr., pct. 2"),
 dict(
  titlu="Războiul civil gotic dintre Athanaric și Fritigern",
  tip="Război civil",
  data_start="c. 370", data_end="c. 375", an_start=370, an_end=375,
  secol="sec. IV d.Hr.", secol_n=4,
  locatie="Câmpia Română (teritoriile vizigotice)",
  zona_aprox=1, judet="—", regiune="Muntenia / Oltenia",
  lat=44.7, lng=25.6,
  participanti="Fracțiunea creștină ariană (Fritigern, cu sprijin roman) vs. fracțiunea păgână (Athanaric)",
  descriere="În rândul vizigoților izbucnește un conflict intern violent pentru conducerea triburilor din Câmpia Română: Fritigern, liderul facțiunii convertite la creștinismul arian, se războiește cu păgânul Athanaric și primește ajutor militar de la romani, măcinând forțele rivalului.",
  rezultat="Slăbirea lui Athanaric; consolidarea lui Fritigern",
  teritoriu="da",
  observatii="Datare aproximativă; zonă aproximativă.",
  sursa="batalii.csv — sec. IV d.Hr., pct. 3"),
 dict(
  titlu="Invazia hunilor (376) și prăbușirea stăpânirii gotice",
  tip="Invazie",
  data_start="376", data_end="376", an_start=376, an_end=376,
  secol="sec. IV d.Hr.", secol_n=4,
  locatie="Estul și nordul Carpaților; linia Prutului/Siretului (valurile de pământ din Moldova)",
  zona_aprox=1, judet="—", regiune="Moldova / Muntenia",
  lat=46.8, lng=27.5,
  participanti="Hunii vs. goți (Athanaric) și populațiile gotice din regiune",
  descriere="Hunii atacă violent stăpânirile gotice de la est și nord de Carpați. Athanaric încearcă să organizeze o linie de apărare fortificată pe aliniamentul Prutului sau Siretului, atribuită uneori valurilor de pământ istorice din Moldova, dar este înfrânt rapid. Panicați, sute de mii de goți conduși de Fritigern se refugiază în 376 la granița Dunării, cerând azil în Imperiul Roman.",
  rezultat="Prăbușirea puterii gotice în regiune; exodul goților peste Dunăre",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. IV d.Hr., pct. 3"),
]
