# -*- coding: utf-8 -*-
"""Partea 4 - Sec. V - X d.Hr. (migrații, gepizi, avari, bulgari, maghiari)"""
EVENTS = [
 dict(
  titlu="Campaniile lui Attila de-a lungul Dunării",
  tip="Invazii / campanii de jaf",
  data_start="441", data_end="447", an_start=441, an_end=447,
  secol="sec. V d.Hr.", secol_n=5,
  locatie="Scythia Minor (Dobrogea) și linia Dunării",
  zona_aprox=1, judet="Constanța / Tulcea", regiune="Dobrogea",
  lat=44.6, lng=28.3,
  participanti="Imperiul Hunic (Attila) vs. Imperiul Roman de Răsărit (Scythia Minor)",
  descriere="Hunii își stabilesc centrul puterii în Câmpia Panonică și controlează militar teritorii vaste, inclusiv Banatul, Crișana, Transilvania și Muntenia. Sub Attila (434–453), lansează atacuri devastatoare asupra provinciilor Imperiului Roman de Răsărit de-a lungul Dunării: orașele fortificate din Dobrogea sunt asediate, jefuite sau parțial distruse în anii 441–447 pentru a forța Constantinopolul să plătească subsidii uriașe.",
  rezultat="Distrugeri în Dobrogea; plata unor subsidii uriașe de către Bizanț",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. V d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la râul Nedao și revolta gepizilor",
  tip="Bătălie / revoltă",
  data_start="454", data_end="454", an_start=454, an_end=454,
  secol="sec. V d.Hr.", secol_n=5,
  locatie="Pe un afluent al Dunării, în zona panonică / bănățeană (locație disputată)",
  zona_aprox=1, judet="—", regiune="Banat / Panonia",
  lat=45.8, lng=20.1,
  participanti="Gepizi (Ardaric) și coaliația germanică vs. fiii lui Attila (Imperiul Hunic)",
  descriere="Imediat după moartea lui Attila (453), imperiul hunic se destramă în urma unei revolte masive a popoarelor germanice vasale, conduse de gepizi. În bătălia din 454 (localizată istoric pe un afluent al Dunării sau în zona panonico-bănățeană), Ardaric îi învinge pe fiii lui Attila; gepizii preiau apoi controlul teritorial asupra Transilvaniei și Banatului, nucleul Regatului Gepid.",
  rezultat="Prăbușirea imperiului hunic; înființarea Regatului Gepid în Transilvania și Banat",
  teritoriu="partial",
  observatii="Locația exactă a bătăliei este disputată; consecințele privesc direct teritoriul României.",
  sursa="batalii.csv — sec. V d.Hr., pct. 2"),
 dict(
  titlu="Conflictele ostrogoților cu gepizii",
  tip="Conflicte teritoriale",
  data_start="c. 455", data_end="c. 500", an_start=455, an_end=500,
  secol="sec. V d.Hr.", secol_n=5,
  locatie="Vestul și sudul României actuale (Banat, Crișana, Transilvania de vest)",
  zona_aprox=1, judet="—", regiune="Banat / Crișana / Transilvania (vest)",
  lat=45.9, lng=21.5,
  participanti="Ostrogoți (inclusiv sub Teodoric cel Mare) vs. gepizi",
  descriere="Ostrogoții, eliberați de sub huni, se află în dispute teritoriale constante cu gepizii și cu Imperiul Roman de Răsărit. Timp de decenii, grupuri masive de ostrogoți controlează sau atacă regiuni din vestul și sudul României actuale, generând ciocniri locale frecvente cu gepizii pentru rutele de jaf și pășunat.",
  rezultat="Instabilitate cronică; fără un câștigător clar",
  teritoriu="da",
  observatii="Zonă aproximativă; fără bătălii nominale.",
  sursa="batalii.csv — sec. V d.Hr., pct. 3"),
 dict(
  titlu="Războaiele defensive de pe limesul dunărean (Scythia Minor)",
  tip="Războaie defensive / asedii",
  data_start="c. 400", data_end="c. 500", an_start=400, an_end=500,
  secol="sec. V d.Hr.", secol_n=5,
  locatie="Dobrogea: Capidava, Histria, Dinogetia și fortificațiile de pe Dunăre",
  zona_aprox=1, judet="Constanța / Tulcea", regiune="Dobrogea",
  lat=44.6, lng=28.3,
  participanti="Imperiul Roman de Răsărit (Bizantin) vs. huni (rămășițe), uzi, sciri, heruli și primele incursiuni proto-bulgare",
  descriere="Dobrogea rămâne sub control bizantin și devine o zonă permanentă de război defensiv. Trupele romano-bizantine resping valuri succesive de atacatori migratori, iar fortificațiile de pe Dunăre (Capidava, Histria, Dinogetia) sunt frecvent atacate și reconstruite.",
  rezultat="Menținerea controlului bizantin în Dobrogea, cu distrugeri și refaceri repetate",
  teritoriu="da",
  observatii="Eveniment tip, pe mai multe decenii.",
  sursa="batalii.csv — sec. V d.Hr., pct. 4"),
 dict(
  titlu="Incursiunile slave și proto-bulgare la Dunăre (începutul sec. VI)",
  tip="Incursiuni / invazii",
  data_start="c. 527", data_end="c. 533", an_start=527, an_end=533,
  secol="sec. VI d.Hr.", secol_n=6,
  locatie="Muntenia, Oltenia și Dobrogea",
  zona_aprox=1, judet="—", regiune="Muntenia / Oltenia / Dobrogea",
  lat=44.5, lng=25.8,
  participanti="Slavi (Antii, Sclaveni) și populații turanice (proto-bulgari, kutriguri) vs. Imperiul Bizantin",
  descriere="Începând cu domnia lui Iustin I și atingând apogeul sub Iustinian I (527–565), triburile slave și populațiile turanice atacă sistematic linia Dunării. Generalul bizantin Chilbudios, comandant al Thraciei din 530, trece de mai multe ori la nord de Dunăre pentru represalii, până când este învins și ucis în luptă (cca. 533).",
  rezultat="Devastări în zona Dunării; moartea lui Chilbudios; reconstrucția fortificațiilor",
  teritoriu="da",
  observatii="Datare aproximativă a morții lui Chilbudios (c. 533).",
  sursa="batalii.csv — sec. VI d.Hr., pct. 1"),
 dict(
  titlu="Războiul gepido-lombard (567) și ascensiunea avarilor",
  tip="Război",
  data_start="567", data_end="567", an_start=567, an_end=567,
  secol="sec. VI d.Hr.", secol_n=6,
  locatie="Transilvania și Banat (Regatul Gepid)",
  zona_aprox=1, judet="—", regiune="Transilvania / Banat",
  lat=46.0, lng=22.8,
  participanti="Longobarzi (Alboin) și Kaganatul Avar (Baian) vs. Regatul Gepid",
  descriere="Conflictul militar major cu consecințe europene: conducătorul longobard Alboin se aliază cu Kaganatul Avar pentru a-i distruge pe gepizi. Gepizii sunt zdrobiți militar pe teritoriul Transilvaniei și al Panoniei, iar locul lor este luat de avari, care devin cea mai mare forță militară din regiune și preiau controlul politic asupra teritoriilor intracarpatice și din vestul României.",
  rezultat="Distrugerea Regatului Gepid; hegemonia avară în bazinul carpatic",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. VI d.Hr., pct. 2"),
 dict(
  titlu="Asediile avaro-slave asupra orașelor din Dobrogea",
  tip="Asedii / invazii",
  data_start="580", data_end="587", an_start=580, an_end=587,
  secol="sec. VI d.Hr.", secol_n=6,
  locatie="Dobrogea: Durostorum, Tropaeum Traiani, Histria, Tomis, Dinogetia",
  zona_aprox=1, judet="Constanța / Tulcea", regiune="Dobrogea",
  lat=44.3, lng=28.2,
  participanti="Avari și slavi vs. Imperiul Bizantin (orașele fortificate din Dobrogea)",
  descriere="Avarii, aliați adesea cu slavii, își îndreaptă atacurile spre Imperiul Bizantin, Dobrogea devenind una dintre principalele porți de invazie. În anii 580–587 asediază și distrug parțial marile orașe fortificate: Durostorum, Tropaeum Traiani, Histria, Tomis, Dinogetia.",
  rezultat="Distrugerea parțială a orașelor dobrogene; declin urban pronunțat",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. VI d.Hr., pct. 3"),
 dict(
  titlu="Campaniile lui Mauriciu la nord de Dunăre (bătăliile de pe Ialomița)",
  tip="Campanii / bătălii",
  data_start="591", data_end="602", an_start=591, an_end=602,
  secol="sec. VI d.Hr.", secol_n=6,
  locatie="Muntenia (zona râului Ialomița) și Dobrogea",
  zona_aprox=1, judet="Ialomița / Constanța", regiune="Muntenia / Dobrogea",
  lat=44.7, lng=27.0,
  participanti="Imperiul Bizantin (Priscus și Petru) vs. slavi și avari",
  descriere="Împăratul bizantin Mauriciu refuză să mai plătească tribut avarilor și mută războiul la nord de Dunăre. Generalii săi trec fluviul în zona Munteniei și Dobrogei, obținând victorii militare importante împotriva slavilor și avarilor chiar pe teritoriul actual al României — de exemplu, bătăliile din zona râului Ialomița sau în apropiere de Dunăre, în anii 593 și 601–602.",
  rezultat="Victorii bizantine temporare la nord de Dunăre",
  teritoriu="da",
  observatii="Locațiile exacte sunt aproximative.",
  sursa="batalii.csv — sec. VI d.Hr., pct. 3"),
 dict(
  titlu="Revolta armatei bizantine de la Dunăre (602) și prăbușirea limesului",
  tip="Revoltă militară / mutinie",
  data_start="602", data_end="602", an_start=602, an_end=602,
  secol="sec. VI–VII d.Hr.", secol_n=6,
  locatie="Tabăra militară bizantină de la Dunăre (teritoriul actual al României)",
  zona_aprox=1, judet="—", regiune="Dunărea (Muntenia / Dobrogea)",
  lat=44.3, lng=27.0,
  participanti="Armata bizantină cantonată la Dunăre (Phocas) vs. Imperiul Bizantin (Mauriciu)",
  descriere="În toamna anului 602, armata bizantină cantonată la Dunăre primește ordinul de a ierna la nord de fluviu, în teritoriul inamic (pe pământ românesc). Soldații se revoltă, conduși de centurionul Phocas, părăsesc frontiera și pornesc spre Constantinopol pentru a-l detrona pe împărat. Evenimentul marchează prăbușirea ireversibilă a limesului dunărean.",
  rezultat="Detronarea lui Mauriciu; prăbușirea apărării dunărene și deschiderea drumului slavilor",
  teritoriu="da",
  observatii="Locația exactă a taberei nu este cunoscută.",
  sursa="batalii.csv — sec. VI d.Hr., consecințe; sec. VII d.Hr., pct. 1"),
 dict(
  titlu="Invaziile avaro-slave și abandonarea orașelor din Dobrogea (602–626)",
  tip="Invazii / asedii",
  data_start="602", data_end="626", an_start=602, an_end=626,
  secol="sec. VII d.Hr.", secol_n=7,
  locatie="Dobrogea: Histria, Tomis, Dinogetia, Tropaeum Traiani",
  zona_aprox=1, judet="Constanța / Tulcea", regiune="Dobrogea",
  lat=44.4, lng=28.2,
  participanti="Avari și slavi vs. Imperiul Bizantin (orașele din Dobrogea)",
  descriere="După revolta din 602, Dobrogea și restul teritoriului rămân complet expuse. Avarii și slavii declanșează atacuri devastatoare: fortărețele romano-bizantine din Dobrogea suferă asedii și distrugeri violente, multe fiind definitiv abandonate sau ruralizate în primele decenii ale secolului VII. Teritoriul României servește drept bază de operațiuni și coridor de trecere pentru atacurile care culminează cu asediul Constantinopolului din 626.",
  rezultat="Sfârșitul vieții urbane antice în Dobrogea; dominare avaro-slavă",
  teritoriu="da",
  observatii="—",
  sursa="batalii.csv — sec. VII d.Hr., pct. 1"),
 dict(
  titlu="Conflictele interne post-avare din Transilvania",
  tip="Conflicte de uzură / revolta populațiilor supuse",
  data_start="c. 626", data_end="c. 680", an_start=626, an_end=680,
  secol="sec. VII d.Hr.", secol_n=7,
  locatie="Transilvania și zonele de vest ale României",
  zona_aprox=1, judet="—", regiune="Transilvania / Banat / Crișana",
  lat=46.3, lng=23.2,
  participanti="Kaganatul Avar vs. triburi slave și populații locale (protoromâne)",
  descriere="După eșecul asediului Constantinopolului din 626, autoritatea Hanatului Avar se clatină. În Transilvania și în zonele de vest au loc conflicte de uzură între avari și triburile slave sau populațiile locale care încearcă să scape de hegemonia nomadă; arheologia atestă distrugeri și schimbări de culturi materiale specifice acestei instabilități.",
  rezultat="Slăbirea kaganatului avar; instabilitate politică",
  teritoriu="da",
  observatii="Eveniment tip, fără bătălii nominale.",
  sursa="batalii.csv — sec. VII d.Hr., pct. 2"),
 dict(
  titlu="Bătălia de la Ongal (680)",
  tip="Bătălie",
  data_start="680", data_end="680", an_start=680, an_end=680,
  secol="sec. VII d.Hr.", secol_n=7,
  locatie="Zona fortificată Ongal — Delta Dunării / nordul Dobrogei / sudul Basarabiei",
  zona_aprox=1, judet="Tulcea", regiune="Dobrogea / Basarabia (historic)",
  lat=45.35, lng=29.10,
  participanti="Protobulgari (hanul Asparuh) vs. Imperiul Bizantin (Constantin al IV-lea)",
  descriere="Triburile protobulgare conduse de hanul Asparuh migrează spre gurile Dunării. Împăratul bizantin Constantin al IV-lea organizează o expediție masivă pe apă și pe uscat, dar confruntarea din zona fortificată Ongal se soldează cu o victorie bulgară zdrobitoare, obținută în zonele mlăștinoase. În urma victoriei, bulgarii trec Dunărea și pun bazele Primului Imperiu Bulgar (681), controlând temporar și zonele de câmpie de la nord de Dunăre.",
  rezultat="Victorie bulgară; înființarea Primului Imperiu Bulgar",
  teritoriu="partial",
  observatii="Localizarea exactă a Ongalului este disputată (Delta Dunării / Basarabia).",
  sursa="batalii.csv — sec. VII d.Hr., pct. 3"),
 dict(
  titlu="Conflictele de autoapărare ale comunităților locale (etnogeneza românească)",
  tip="Conflict local / autoapărare",
  data_start="c. 600", data_end="c. 700", an_start=600, an_end=700,
  secol="sec. VI–VII d.Hr.", secol_n=7,
  locatie="Zonele muntoase și împădurite ale Carpaților",
  zona_aprox=1, judet="—", regiune="Transilvania / Carpați",
  lat=46.0, lng=25.0,
  participanti="Comunități locale daco-romane (obști sătești) vs. migratori (slavi, avari)",
  descriere="Populația autohtonă, fără armată centralizată, se organizează în comunități locale; conflictele cu migratorii sunt preponderent de autoapărare. Localnicii se retrag frecvent în zonele muntoase și împădurite pentru a evita rutele de invazie, generând un amestec etno-cultural complex cu slavii rămași la nord de Dunăre, proces care duce la definitivarea etnogenezei românești.",
  rezultat="Supraviețuirea și consolidarea comunităților românești locale",
  teritoriu="da",
  observatii="Eveniment tip; nu există nume de lupte sau lideri consemnați.",
  sursa="batalii.csv — sec. VII d.Hr., pct. 4"),
 dict(
  titlu="Campaniile lui Constantin al V-lea împotriva bulgarilor la Dunărea de Jos",
  tip="Campanii / războaie bizantino-bulgare",
  data_start="741", data_end="775", an_start=741, an_end=775,
  secol="sec. VIII d.Hr.", secol_n=8,
  locatie="Dunărea de Jos și Dobrogea",
  zona_aprox=1, judet="Constanța / Tulcea / Călărași", regiune="Dobrogea / Dunărea de Jos",
  lat=44.3, lng=27.7,
  participanti="Imperiul Bizantin (Constantin al V-lea) vs. Primul Imperiu Bulgar (Tervel și succesorii)",
  descriere="Dobrogea și regiunile de câmpie din stânga Dunării devin teatre de operațiuni și zone de dispute militare între bulgari și bizantini. Constantin al V-lea organizează nouă campanii militare împotriva bulgarilor; multe înfruntări se desfășoară în zona Dunării de Jos (inclusiv Dobrogea), flotele bizantine navigând pe Dunăre și pe mare pentru a ataca taberele bulgare și slave.",
  rezultat="Presiune militară bizantină constantă; control alternant al Dunării de Jos",
  teritoriu="da",
  observatii="Fără bătălii nominale pe teritoriul României (în afară de context).",
  sursa="batalii.csv — sec. VIII d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de la Anchialos (context — în afara teritoriului României)",
  tip="Bătălie (context regional)",
  data_start="763", data_end="763", an_start=763, an_end=763,
  secol="sec. VIII d.Hr.", secol_n=8,
  locatie="Anchialos (azi Pomorie, Bulgaria) — în afara teritoriului actual al României",
  zona_aprox=1, judet="—", regiune="—",
  lat=42.56, lng=27.64,
  participanti="Imperiul Bizantin (Constantin al V-lea) vs. Primul Imperiu Bulgar",
  descriere="Deși bătălia s-a dat mai la sud, victoria bizantină a reconfigurat controlul militar din întreaga regiune pontică și dobrogeană, influențând direct echilibrul de putere pe teritoriul actual al României.",
  rezultat="Victoria bizantină; reconfigurare regională",
  teritoriu="nu",
  observatii="Inclus ca eveniment de context regional.",
  sursa="batalii.csv — sec. VIII d.Hr., pct. 1"),
 dict(
  titlu="Conflictele de frontieră ale Kaganatului Avar (declinul avar)",
  tip="Conflicte de frontieră / războaie civile",
  data_start="c. 700", data_end="c. 800", an_start=700, an_end=800,
  secol="sec. VIII d.Hr.", secol_n=8,
  locatie="Transilvania, Banat, Crișana",
  zona_aprox=1, judet="—", regiune="Transilvania / Banat / Crișana",
  lat=46.2, lng=22.5,
  participanti="Kaganatul Avar vs. populații slave și romanice locale; presiunea francă (Carol cel Mare, de la 791)",
  descriere="Avarii controlează politic populația sedentară; există numeroase ciocniri de intensitate mică și medie la granițele kaganatului. Campaniile decisive ale lui Carol cel Mare (începând din 791) și destabilizarea internă a avarilor generează conflicte violente care cuprind și vestul Transilvaniei sau Banatul, ducând la prăbușirea puterii avare.",
  rezultat="Prăbușirea puterii avare; deschiderea teritoriului către expansiunea bulgară",
  teritoriu="da",
  observatii="Eveniment tip, fără bătălii nominale.",
  sursa="batalii.csv — sec. VIII d.Hr., pct. 2"),
 dict(
  titlu="Incursiunile de pradă asupra comunităților locale („veacurile întunecate”)",
  tip="Incursiuni de jaf / conflict endemic",
  data_start="c. 700", data_end="c. 800", an_start=700, an_end=800,
  secol="sec. VIII d.Hr.", secol_n=8,
  locatie="Teritoriul populației protoromâne (așezări rurale, culturile Ipotești-Cândești și Dridu)",
  zona_aprox=1, judet="—", regiune="Muntenia / Oltenia / Dobrogea",
  lat=44.8, lng=25.5,
  participanti="Populația locală protoromână (cnezi și juzi timpurii) vs. triburi slave și nomade",
  descriere="Lipsa unor izvoare scrise detaliate face ca luptele purtate de liderii locali să nu fie consemnate cu nume proprii. Descoperirile de arme, fortificațiile de pământ (palisade) și așezările incendiate demonstrează o stare de conflict endemic defensiv, populația fiind adesea prinsă la mijloc în incursiunile de pradă ale triburilor slave și nomade.",
  rezultat="Apărare locală; fortificarea și abandonarea periodică a așezărilor",
  teritoriu="da",
  observatii="Eveniment tip, documentat arheologic.",
  sursa="batalii.csv — sec. VIII d.Hr., pct. 3"),
 dict(
  titlu="Rezistența voievodatului lui Gelu împotriva maghiarilor",
  tip="Război de apărare / bătălie",
  data_start="c. 896", data_end="c. 896", an_start=896, an_end=896,
  secol="sec. IX d.Hr.", secol_n=9,
  locatie="Transilvania centrală; lupta de lângă râul Căpuș (jud. Cluj)",
  zona_aprox=1, judet="Cluj", regiune="Transilvania",
  lat=46.79, lng=23.45,
  participanti="Voievodatul lui Gelu (români) vs. triburile maghiare (Tuhutum)",
  descriere="După pătrunderea maghiarilor în Bazinul Carpatic (c. 896), Gelu, numit în Gesta Hungarorum „duce al românilor”, refuză să cedeze pământurile și poartă bătălii violente împotriva căpeteniei maghiare Tuhutum. Este în cele din urmă înfrânt și ucis lângă râul Căpuș.",
  rezultat="Înfrângerea și moartea lui Gelu; cucerirea Transilvaniei centrale de către maghiari",
  teritoriu="da",
  observatii="Sursa principală este Gesta Hungarorum (cronica din sec. XII), cu datare disputată de istoriografie.",
  sursa="batalii.csv — sec. IX d.Hr., pct. 1"),
 dict(
  titlu="Rezistența voievodatului lui Menumorut — asediul Biharei",
  tip="Război de apărare / asediu",
  data_start="c. 896", data_end="c. 896", an_start=896, an_end=896,
  secol="sec. IX d.Hr.", secol_n=9,
  locatie="Crișana: cetatea Biharea (lângă actuala Biharia, jud. Bihor)",
  zona_aprox=0, judet="Bihor", regiune="Crișana",
  lat=47.15, lng=21.93,
  participanti="Voievodatul lui Menumorut (români) vs. triburile maghiare (Árpád / trupele acestuia)",
  descriere="Oștile lui Menumorut înfruntă trupele maghiare trimise de Árpád; conflictul se concentrează în jurul asediului cetății Biharea. Menumorut rezistă inițial, stabilind ulterior o pace prin alianță dinastică (fiica sa este dată în căsătorie fiului lui Árpád).",
  rezultat="Pace prin alianță dinastică; supunere nominală a voievodatului",
  teritoriu="da",
  observatii="Conform Gesta Hungarorum; datare disputată.",
  sursa="batalii.csv — sec. IX d.Hr., pct. 1"),
 dict(
  titlu="Rezistența voievodatului lui Glad (bătălia de la Mureș/Timiș)",
  tip="Război de apărare / bătălie",
  data_start="c. 896", data_end="c. 896", an_start=896, an_end=896,
  secol="sec. IX d.Hr.", secol_n=9,
  locatie="Banat: vadurile râurilor Mureș și Timiș",
  zona_aprox=1, judet="Timiș / Arad", regiune="Banat",
  lat=45.9, lng=21.2,
  participanti="Voievodatul lui Glad (vlahi, slavi, bulgari) vs. triburile maghiare (Árpád)",
  descriere="Glad conduce o armată formată din vlahi, slavi și bulgari împotriva invadatorilor. Luptele principale se dau la vadurile râurilor Mureș și Timiș, unde este înfrânt, ulterior acceptând o formă de suzeranitate.",
  rezultat="Înfrângerea lui Glad; suzeranitate maghiară asupra Banatului",
  teritoriu="da",
  observatii="Conform Gesta Hungarorum; reluat și la sec. X d.Hr.",
  sursa="batalii.csv — sec. IX d.Hr., pct. 1"),
 dict(
  titlu="Revolta triburilor din Dacia dunăreană împotriva bulgarilor",
  tip="Revoltă / răscoală",
  data_start="824", data_end="824", an_start=824, an_end=824,
  secol="sec. IX d.Hr.", secol_n=9,
  locatie="Dacia dunăreană (sudul Munteniei / Banatul de est)",
  zona_aprox=1, judet="—", regiune="Muntenia / Banat",
  lat=44.6, lng=24.0,
  participanti="Triburi locale (obotiți/praedeneceni) vs. Primul Imperiu Bulgar (Krum, Omurtag)",
  descriere="Analele Regale Franceze notează că, în 824, triburile din Dacia dunăreană (precum obotiții/praedenecenii) s-au ridicat la luptă și au căutat alianțe externe (cu Imperiul Carolingian) pentru a scăpa de sub suzeranitatea bulgară.",
  rezultat="Revoltă parțial înăbușită; căutarea de alianțe externe",
  teritoriu="da",
  observatii="Identificarea triburilor și localizarea sunt discutabile.",
  sursa="batalii.csv — sec. IX d.Hr., pct. 2"),
 dict(
  titlu="Luptele pentru controlul minelor de sare și aur (sudul Transilvaniei și Banat)",
  tip="Conflicte pentru resurse",
  data_start="c. 800", data_end="c. 899", an_start=800, an_end=899,
  secol="sec. IX d.Hr.", secol_n=9,
  locatie="Sudul Transilvaniei și Banat",
  zona_aprox=1, judet="—", regiune="Transilvania / Banat",
  lat=45.8, lng=23.0,
  participanti="Primul Imperiu Bulgar vs. structuri politice locale",
  descriere="Sudul Transilvaniei și Banatul sunt zone de conflict armat direct din cauza controlului asupra minelor de sare și aur, disputate între bulgari și structurile locale, în contextul extinderii autorității bulgare la nord de Dunăre.",
  rezultat="Control alternant al resurselor; instabilitate în zonă",
  teritoriu="da",
  observatii="Eveniment tip.",
  sursa="batalii.csv — sec. IX d.Hr., pct. 2"),
 dict(
  titlu="Invaziile pecenegilor în Etelköz (dislocarea maghiarilor)",
  tip="Invazii / incursiuni",
  data_start="c. 870", data_end="c. 899", an_start=870, an_end=899,
  secol="sec. IX d.Hr.", secol_n=9,
  locatie="Spațiul dintre Nistru, Prut și Siret (Etelköz, azi în Ucraina/Republica Moldova)",
  zona_aprox=1, judet="—", regiune="Moldova (historic)",
  lat=46.5, lng=29.5,
  participanti="Pecenegi vs. maghiari (Etelköz) și comunitățile sedentare din regiune",
  descriere="În a doua jumătate a secolului IX, regiunile din afara arcului carpatic (Moldova și Muntenia) devin teatre de război din cauza pecenegilor: aceștia lansează atacuri devastatoare în spațiul dintre Nistru, Prut și Siret, dislocând maghiarii din Etelköz și generând conflicte locale sângeroase cu comunitățile sedentare, forțând fortificarea așezărilor.",
  rezultat="Dislocarea maghiarilor spre Panonia; presiune pecenegă",
  teritoriu="partial",
  observatii="Zona se află în mare parte în afara granițelor actuale ale României.",
  sursa="batalii.csv — sec. IX d.Hr., pct. 3"),
 dict(
  titlu="Bătălia de pe râul Timiș (voievodatul lui Glad vs. maghiari)",
  tip="Bătălie",
  data_start="c. 900", data_end="c. 905", an_start=900, an_end=905,
  secol="sec. X d.Hr.", secol_n=10,
  locatie="Râul Timiș (Banat)",
  zona_aprox=1, judet="Timiș", regiune="Banat",
  lat=45.6, lng=21.3,
  participanti="Voievodatul lui Glad (români, bulgari, pecenegi) vs. maghiari (Zuard, Cadusa — nepotul lui Tuhutum)",
  descriere="La începutul secolului X, Glad, care conducea un teritoriu între Dunăre, Mureș și Tisa, opune rezistență armatei maghiare. Strânge o armată de români, bulgari și pecenegi, dar este învins în bătălia de pe râul Timiș și nevoit să ceară pace, acceptând o formă de suzeranitate.",
  rezultat="Înfrângerea lui Glad; suzeranitate maghiară",
  teritoriu="da",
  observatii="Conform Gesta Hungarorum; datare disputată.",
  sursa="batalii.csv — sec. X d.Hr., pct. 1"),
 dict(
  titlu="Bătălia de pe râul Almaș (voievodatul lui Gelu vs. Tuhutum)",
  tip="Bătălie",
  data_start="c. 900", data_end="c. 905", an_start=900, an_end=905,
  secol="sec. X d.Hr.", secol_n=10,
  locatie="Râul Almaș (județul Sălaj)",
  zona_aprox=1, judet="Sălaj", regiune="Transilvania",
  lat=47.14, lng=23.26,
  participanti="Voievodatul lui Gelu (români) vs. triburile maghiare (Tuhutum)",
  descriere="Tuhutum atacă teritoriul condus de „Gelu, un anumit român”. Armata lui Gelu, slab echipată, este învinsă în bătălia de pe râul Almaș; Gelu încearcă să se retragă spre fortăreața sa de pe Someș (probabil Dăbâca), dar este prins și ucis de călăreții maghiari.",
  rezultat="Victorie maghiară; moartea lui Gelu; cucerirea Transilvaniei de nord-vest",
  teritoriu="da",
  observatii="Conform Gesta Hungarorum.",
  sursa="batalii.csv — sec. X d.Hr., pct. 1"),
 dict(
  titlu="Asediul cetății Biharia (voievodatul lui Menumorut)",
  tip="Asediu",
  data_start="c. 900", data_end="c. 905", an_start=900, an_end=905,
  secol="sec. X d.Hr.", secol_n=10,
  locatie="Cetatea Biharia (județul Bihor); cetățile Săcueni și Satu Mare",
  zona_aprox=1, judet="Bihor / Satu Mare", regiune="Crișana",
  lat=47.15, lng=21.93,
  participanti="Voievodatul lui Menumorut vs. triburile maghiare (Árpád)",
  descriere="Menumorut, care stăpânea teritoriul dintre Mureș și Someș, respinge inițial cererile de supunere ale maghiarilor; cetățile sale (Săcueni, Satu Mare) sunt asediate. După un asediu de 13 zile al cetății Biharia, acceptă pacea, oferindu-și fiica în căsătorie fiului lui Árpád.",
  rezultat="Acceptarea păcii; alianță dinastică cu maghiarii",
  teritoriu="da",
  observatii="Conform Gesta Hungarorum.",
  sursa="batalii.csv — sec. X d.Hr., pct. 1"),
 dict(
  titlu="Invazia lui Sviatoslav la Dunărea de Jos (968–971)",
  tip="Invazie / cucerire",
  data_start="968", data_end="971", an_start=968, an_end=971,
  secol="sec. X d.Hr.", secol_n=10,
  locatie="Dobrogea și gurile Dunării (Pereiaslaveț, identificat probabil cu Nufăru, jud. Tulcea)",
  zona_aprox=1, judet="Tulcea", regiune="Dobrogea",
  lat=45.15, lng=28.90,
  participanti="Cnezatul de la Kiev (Sviatoslav I) vs. Imperiul Bizantin și Țaratul Bulgar",
  descriere="Împăratul bizantin Nichifor al II-lea Focas îl plătește pe cneazul rus Sviatoslav să atace țaratul Bulgar. Sviatoslav invadează teritoriul de la Dunăre, cucerind numeroase cetăți (inclusiv Pereiaslaveț) și decide să-și mute capitala acolo, amenințând direct Bizanțul.",
  rezultat="Cucerire temporară a Dunării de Jos de către Sviatoslav",
  teritoriu="da",
  observatii="Identificarea Pereiaslavețului cu Nufăru este probabilă, nu sigură.",
  sursa="batalii.csv — sec. X d.Hr., pct. 2"),
 dict(
  titlu="Campania lui Ioan Tzimiskes și asediul Dristorului",
  tip="Campanie / asediu",
  data_start="971", data_end="971", an_start=971, an_end=971,
  secol="sec. X d.Hr.", secol_n=10,
  locatie="Cetatea Dristor (azi Silistra, la granița actuală a României)",
  zona_aprox=1, judet="—", regiune="Dobrogea (graniță)",
  lat=44.12, lng=27.26,
  participanti="Imperiul Bizantin (Ioan I Tzimiskes) vs. cnezatul de la Kiev (Sviatoslav)",
  descriere="Noul împărat bizantin Ioan I Tzimiskes pornește o contraofensivă fulgerătoare și asediază cetatea Dristor, unde se refugiase Sviatoslav. După lupte grele pe uscat și pe Dunăre (bizantinii folosesc focul grecesc), rușii sunt învinși și se retrag; Dobrogea reintră sub controlul direct al Imperiului Bizantin.",
  rezultat="Retragerea rușilor; restaurarea controlului bizantin asupra Dobrogei",
  teritoriu="partial",
  observatii="Dristorul este azi în Bulgaria, dar asediul s-a desfășurat imediat la granița Dobrogei românești.",
  sursa="batalii.csv — sec. X d.Hr., pct. 2"),
 dict(
  titlu="Raidurile pecenegilor în regiunile extracarpatice",
  tip="Raiduri / conflicte de frontieră",
  data_start="c. 900", data_end="c. 999", an_start=900, an_end=999,
  secol="sec. X d.Hr.", secol_n=10,
  locatie="Moldova și Muntenia (regiunile extracarpatice)",
  zona_aprox=1, judet="—", regiune="Moldova / Muntenia",
  lat=46.0, lng=26.8,
  participanti="Pecenegi vs. populații locale românești, bulgari și bizantini",
  descriere="Pecenegii, stabiliți în stepele nord-pontice și în regiunile extracarpatice, întreprind numeroase expediții de jaf și conflicte de frontieră împotriva populațiilor locale românești, dar și împotriva bulgarilor și bizantinilor. Adesea sunt folosiți ca mercenari în conflictele dintre cnezi sau țari.",
  rezultat="Instabilitate cronică și deplasări de populație",
  teritoriu="da",
  observatii="Eveniment tip.",
  sursa="batalii.csv — sec. X d.Hr., pct. 3"),
]
